import Ar from '../img/ar.jpg';
import Br from '../img/br.jpg';
import Cl from '../img/cl.jpg';
import Co from '../img/co.jpg';
import Es from '../img/es.jpg';
import Btc from '../img/icn-btc.png';
import Eth from '../img/eth.jpg';
import Do from '../img/do.jpg';
import Mx from '../img/mx.jpg';
import Pe from '../img/pe.jpg';
import Us from '../img/us.jpg';
import Ve from '../img/ve.jpg';
import Cr from '../img/cr.png';
import Pn from '../img/pan.jpg';
import Ca from '../img/ca.jpg';
import Cn from '../img/cn.jpg';
import Ru from '../img/ru.jpg';
import Jp from '../img/jp.jpg';
import In from '../img/in.jpg';
import Ch from '../img/ch.jpg';
import TetherImg from '../img/icn_tether.png';
export default {
  currenciesFlag: {
    // BRZ: {
    //   key: "br",
    //   value: "BRZ",
    //   flag: "br",
    //   text: "Real Brasileño",
    //   img: Br,
    //   alias: "BRZ",
    //   isCripto: false,
    //   symbol: "R$",
    //   priority: 10,
    // },
    BRL: {
      key: 'br',
      value: 'BRL',
      flag: 'br',
      text: 'Real Brasileño',
      img: Br,
      alias: 'BRL',
      isCripto: false,
      symbol: 'R$',
      priority: 10,
    },
    CLP: {
      key: 'cl',
      value: 'CLP',
      flag: 'cl',
      text: 'Peso Chileno',
      img: Cl,
      alias: 'CLP',
      isCripto: false,
      symbol: 'CL$',
      priority: 6,
    },
    COP: {
      key: 'co',
      value: 'COP',
      flag: 'co',
      text: 'Peso Colombiano',
      img: Co,
      alias: 'COP',
      isCripto: false,
      symbol: 'COL$',
      priority: 5,
    },
    EUR: {
      key: 'es',
      value: 'EUR',
      flag: 'eu',
      text: 'Euro',
      img: Es,
      alias: 'EUR',
      isCripto: false,
      symbol: '€',
      priority: 7,
    },
    DOD: {
      key: 'do',
      value: 'DOD',
      flag: 'do',
      text: 'Dolar Dominicano',
      img: Do,
      alias: 'DOD',
      isCripto: false,
      symbol: 'RD$',
      priority: 9,
    },
    DOP: {
      key: 'dop',
      value: 'DOP',
      flag: 'do',
      text: 'Peso Dominicano',
      img: Do,
      alias: 'DOP',
      isCripto: false,
      symbol: 'RD$',
      priority: 9,
    },
    PEN: {
      key: 'pe',
      value: 'PEN',
      flag: 'pe',
      text: 'Sol Peruano',
      img: Pe,
      alias: 'PEN',
      isCripto: false,
      symbol: 'S/',
      priority: 8,
    },
    PE_USD: {
      key: 'pe_usd',
      value: 'PE_USD',
      flag: 'pe_usd',
      text: 'Dolar Peruano',
      img: Pe,
      alias: 'PE_USD',
      isCripto: false,
      symbol: '$',
      priority: 8,
    },
    PE_EUR: {
      key: 'pe_eur',
      value: 'PE_EUR',
      flag: 'pe_eur',
      text: 'Euro Peruano',
      img: Pe,
      alias: 'PE_EUR',
      isCripto: false,
      symbol: '€',
      priority: 8,
    },
    USD: {
      key: 'us',
      value: 'USD',
      flag: 'us',
      text: 'US Dollar',
      img: Us,
      alias: 'USD',
      isCripto: false,
      symbol: '$',
      priority: 1,
    },
    VES: {
      key: 've',
      value: 'VES',
      flag: 've',
      text: 'Bolívar Venezolano',
      img: Ve,
      alias: 'VES',
      isCripto: false,
      symbol: 'Bs.',
      priority: 2,
    },
    ARS: {
      key: 'ar',
      value: 'ARS',
      flag: 'ar',
      text: 'Peso Argentino',
      img: Ar,
      alias: 'ARS',
      isCripto: false,
      symbol: 'Ar$',
      priority: 3,
    },
    MXN: {
      key: 'mx',
      value: 'MXN',
      flag: 'mx',
      text: 'Peso Mexicano',
      img: Mx,
      alias: 'MXN',
      isCripto: false,
      symbol: 'MXN$',
      priority: 4,
    },
    ETH: {
      key: 'eth',
      value: 'ETH',
      icon: 'ethereum',
      text: 'Ethereum',
      img: Eth,
      alias: 'ETH',
      isCripto: true,
      symbol: 'Eth',
      priority: 14,
    },
    BTC: {
      key: 'btc',
      value: 'BTC',
      icon: 'bitcoin',
      text: 'BITCOIN',
      img: Btc,
      alias: 'BTC',
      isCripto: true,
      symbol: 'Ƀ',
      priority: 15,
    },
    CRC: {
      key: 'crc',
      value: 'CRC',
      flag: 'cr',
      text: 'Colón costarricense',
      img: Cr,
      alias: 'CRC',
      isCripto: false,
      symbol: '₡',
      priority: 11,
    },
    PAB: {
      key: 'pab',
      value: 'PAB',
      flag: 'pa',
      text: 'Balboa',
      img: Pn,
      alias: 'PAB',
      isCripto: false,
      symbol: 'B/.',
      priority: 12,
    },
    PA_USD: {
      key: 'pad',
      value: 'PAD',
      flag: 'pa',
      text: 'Dolár (Pánama)',
      img: Pn,
      alias: 'PAD',
      isCripto: false,
      symbol: '$',
      priority: 13,
    },
    INR: {
      key: 'inr',
      value: 'INR',
      text: 'Rupia',
      img: In,
      alias: 'INR',
      priority: 14,
      isCripto: false,
      symbol: '$',
    },
    CAD: {
      key: 'ca',
      value: 'CAD',
      text: 'Dolar Canadiense',
      img: Ca,
      alias: 'CAD',
      priority: 15,
      isCripto: false,
      symbol: '$',
    },
    CNY: {
      key: 'cny',
      value: 'CNY',
      text: 'Yuanes',
      img: Cn,
      alias: 'CNY',
      priority: 16,
      isCripto: false,
      symbol: '$',
    },
    RUB: {
      key: 'rub',
      value: 'RUB',
      text: 'Rublo ruso',
      img: Ru,
      alias: 'RUB',
      priority: 17,
      isCripto: false,
      symbol: '$',
    },
    JPY: {
      key: 'jpy',
      value: 'JPY',
      text: 'Yen japonés',
      img: Jp,
      alias: 'JPY',
      priority: 18,
      isCripto: false,
      symbol: '$',
    },
    CHF: {
      key: 'chk',
      value: 'CHF',
      text: 'Franco suizo',
      img: Ch,
      alias: 'CHF',
      priority: 19,
      isCripto: false,
      symbol: '$',
    },
    USDT: {
      key: 'usdt',
      value: 'USDT',
      icon: 'usdt',
      text: 'USDT',
      img: TetherImg,
      alias: 'USDT',
      isCripto: false,
      symbol: '₮',
      priority: 20,
    },
  },
};
