export default {
ters: {
      item1: "GENERAL USER AGREEMENT",
  item2: "This is a Service Agreement between You (also referred to in this document as “Client” or “User”) and the multi-platform online cryptographic services: moneyclick.com or its associated websites: dollarbtc.com and bitcoinrecharge.com, (collectively referred to hereinafter as “The Platform”) and their respective extensions such as mobile applications for Android or IOS. The Platform is made up of a set of computer programs that provide different services, such as online sales, communication services, entertainment, information and crypto financial services. To enjoy the services offered by The Platform, the Client must have a balance which is offered through the sale of our electronic service coupons, marketed in the currencies of legal tender in the different countries where The Platform provides services through its Local Authorized Operators or Representatives. This User Agreement (“Agreement”) governs your use of the services provided by The Platform described below (“Platform Services”). By registering to use an account on The Platform you agree that you have read, understand and accept all the terms and conditions contained in this Agreement, including the clauses of: Arbitration; Privacy Policy, Cookies Policy and Electronic Signature Consent Policy.",
  item3: "I PART",
  item4: "GENERAL USE",
  item5: "1. Requirements to be a Platform User:",
  item6: "1.1. Eligibility. ",
  item7 : "To be eligible to use the Platform Services, you must be at least 18 years old.",
  item8: "1.2. Terms. ",
  item9: "We may amend or modify this Agreement at any time by posting the revised agreement on The Platform's website or by providing you with a copy (a “Revised Agreement”) via any registered channel of communication. The revised Agreement will be effective from the time it is posted, but will not apply retroactively. Your continued use of the Services after the posting of a revised Agreement constitutes your acceptance of such modified agreement. If you do not agree to such modification, your sole and exclusive remedy is to terminate your use of the Platform Services and close your account.",

  item10: "1.3. Registration of Moneyclick.com Account. ",

  item11: "You must register for an account with The Platform in order to enjoy and use the Services provided on The Platform. By using an account on The Platform, you agree and represent that you will use The Platform only for yourself and not on behalf of a third party, unless you have obtained prior approval from The Platform. You are fully responsible for all activity that occurs on your Platform account. We may, in our sole discretion, refuse to open an Account on The Platform, or limit the number of accounts, suspend or terminate any account on The Platform.",

  item12: "1.4. Identity Verification. ",
  
  item13: "During the registration of your Platform account, you agree to provide us with the information we request for the purpose of identity verification and detection of money laundering, financing of terrorism, fraud or any other financial crime and allow us to keep a record of said information. . You will need to complete certain verification procedures before you are allowed to use the Platform Services. Your access to one or more Platform Services and the limits that apply to your use of the Platform Services may change as a result of information collected about you on an ongoing basis. The information we request may include certain personal information, including, but not limited to, your name, address, telephone number, email address, date of birth, taxpayer identification number, a government ID, and information about your bank account. (such as bank name, account type, routing number, and account number) and, in some cases (where permitted by law), special categories of personal data, such as your biometric information. By providing us with this or any other information that may be required, you confirm that the information is accurate and authentic. You agree to keep us updated if the information you provide us changes. You authorize us to make such inquiries, either directly or through third parties, as we deem necessary to verify your identity or protect you and us from fraud or other financial crime, and to take such action as we deem reasonably necessary based on the results of such queries. When we make these inquiries, you acknowledge and agree that your personal information may be disclosed to credit reference and fraud or financial crime prevention agencies and that these agencies may respond to our inquiries in full. This is just an identity check and should not have any adverse effect on your credit score. You also authorize your wireless carrier to use your mobile phone number, name, address, email, network status, customer type, customer role, billing type, mobile device identifiers (IMSI and IMEI) and other details of the status of the subscriber, if available, solely to allow verification of your identity and to compare the information you have provided to The Platform with the information in your account profile for the duration of the commercial relationship. If you wish to obtain additional information about our Privacy Policy and data protection, you can review our Data Protection Services Contract or consult directly by our Customer Service email about said policies.",
  
  item14: "1.5. Access. ",
  
  item15: "To access the Platform Services, you must have the necessary equipment (such as a smartphone or laptop or desktop) and associated telecommunications service subscriptions to access the Internet. The Platform Services can be accessed directly through our website or our mobile applications. Access to the Platform Services may be degraded or unavailable during times of volatility or significant volume. This could impact the availability of our services over periods of time and may also cause delays in support response time. Although we strive to provide you with excellent service, we do not represent that the site(s) operated by The Platform will be available without interruption and we do not guarantee that any order will be executed, accepted, registered or remain open. The Platform will not be responsible for losses that result or arise from delays in transactions or any unfinished, interrupted or delayed service for any of these causes or others beyond our control such as failures in internet coverage, electrical failures or even own problems. of faulty or overloaded equipment in its memory or due to excessive use by the Client, or failures of service providers such as telephone companies, data transmission companies, electricity companies or others related.",
  

  item16: "2. Wallet and Custodial Services",
  
  item17: "2.1. Wallet Services. ",
  
  item18: "As part of your account on The Platform, we will provide qualifying Users with access to hosted digital currency wallets to store digital assets.",
  
  item19: "2.2. Built-in digital currency wallet. ",
  
  item20: "Your digital currency wallet allows you to store, track, transfer, and manage your digital currency balances. “Digital Currency” refers only to the particular digital currencies that are listed as available for trading or safekeeping in your Multi-Currency Platform Account. Services and assets supported may vary by jurisdiction. We securely store digital currency private keys, which are used to process transactions, in a combination of online and offline storage. As a result of our security protocols, it may be necessary for us to retrieve private keys or related information from offline storage to facilitate a Digital Currency Transfer in accordance with your instructions, and you acknowledge that this may delay the initiation or crediting of such Transfers. of Digital Currency. Additional rules associated with such products and services may apply.",
  
  item21: "2.3. Supported Digital Currencies. ",
  
  item22: "Your Platform account is intended solely for the proper use of supported digital currencies as designated on the site. Under no circumstances should you attempt to use your Digital Currency Wallet to store, send, request or receive digital currencies that we do not support. The Platform assumes no liability in connection with any attempt to use your Digital Currency Wallet with digital currencies that we do not support. If you have any questions about the digital currencies that we currently support, consult our associated websites or request information from our official Customer Service channels.",

  item23: "2.4. Supplemental Protocols Excluded. ",
  
  item24: "Unless specifically announced on The Platform sites or other official public statement of The Platform, Supported Digital Currencies exclude all other protocols and features that complement or interact with Supported Digital Currency. This exclusion includes, but is not limited to: any smart contract functionality. that may complement or interact with a digital currency that we support. Do not use your Platform account to try to receive, request, send, store or participate in any other type of transaction or functionality that involves any unsupported protocol, since The Platform is not configured to detect, secure or process these transactions and functionalities. . Any transaction attempt made in non-supported currencies will be rejected and we are not responsible for losses or any delay or error resulting from sending non-supported currencies or protocols not associated with the Platform. You acknowledge and agree that add-on protocols are excluded from Supported Digital Currency and that The Platform bears no responsibility for losses related to add-on or unsupported protocols.",
  
  item25: "2.5 Operation of Digital Currency Protocols. ",
  
  item26: "We do not own or control the underlying software protocols that govern the operation of the digital currencies supported on our platform. The underlying protocols are generally open source and can be used, copied, modified, and distributed by anyone. We assume no responsibility for the operation of the underlying protocols and cannot guarantee the functionality or security of network operations. In particular, the underlying protocols may be subject to sudden changes in operating rules (including “forks”). Any of these major operational changes may materially affect the availability, value, functionality, and/or name of the Digital Currency that you store in your Digital Currency Wallet. The Platform does not control the timing or characteristics of these material operational changes. It is your responsibility to be aware of any upcoming operational changes and you should carefully consider publicly available information and information The Platform may provide to determine whether you will continue to use a Platform Account for the affected Digital Currency. In the event of any such operational change, The Platform reserves the right to take whatever action is necessary to protect the safety and security of assets held on The Platform, including the temporary suspension of digital currency operations. involved and other necessary steps; The Platform will use reasonable efforts to notify you of its response to any material operational changes; however, such changes are beyond the control of The Platform and may occur without notice. The Platform's response to any material operational change is at its sole discretion and includes a decision not to support any new digital currency, fork or other actions. You acknowledge and accept the risks of operational changes in digital currency protocols and agree that The Platform is not responsible for any such operational changes and is not liable for any loss in value you may experience as a result of any such changes in operational rules. You acknowledge and agree that The Platform has the sole discretion to determine your response to any operational changes and that we have no responsibility to assist you with unsupported currencies or protocols.",
  
  item27: "2.6. Custody and Title of Digital Currency. ",
  
  item28: "All Digital Currencies held in your Digital Currency Wallet are custodial assets held by The Platform for your benefit, as described in more detail below.",

  item29: "2.6.1 Property. ",
  
  item30: "Ownership of the digital currency will remain with you at all times and will not be transferred to The Platform. As the owner of the digital currency in your digital wallet, you shall bear all risk of loss of said digital currency. The Platform will not have any responsibility for the fluctuations of the digital currency. None of the Digital Currencies in your Digital Currency Wallet is owned by The Platform, or will or may be loaned to The Platform; The Platform does not represent or treat the assets of the user's Digital Currency Portfolios as belonging to The Platform or any of its associated companies, agents or Authorized Operators. The Platform cannot provide a security interest in the Digital Currency held in your Digital Currency Wallet. Except as required by a court order issued by a competent authority, or except as provided herein, The Platform will not sell, transfer, lend, mortgage or otherwise dispose of Digital Currency in your Digital Currency Wallet unless instructed to do so by you.",
  

  item31:"2.6.2 Control. ",
  
  item32: "You control the digital currencies held in your digital currency wallet. At any time, subject to outages, downtime, and other applicable policies, you may withdraw your digital currency by sending it to a different blockchain address. As long as you continue to escrow your digital currencies with The Platform, The Platform will retain control over the electronic private keys associated with the blockchain addresses operated by The Platform, including the blockchain addresses that contain your digital currency.",
  
  item33: "2.6.3 Recognition of risk. ",
  
  item34: "You acknowledge that Digital Currency is not subject to any protections or insurance provided by the Federal Deposit Insurance Corporation or the Securities Investor Protection Corporation or other local fund insurers or regulators of any legal entity. Just as they are not backed by official entities, companies or any other public or private body.",

  item35: "2.6.4 Non-Segregated Digital Currencies. ",
  
  item36: "In order to safeguard assets more securely, The Platform may use shared blockchain addresses, controlled by The Platform, to hold digital currencies on behalf of clients and/or on behalf of The Platform. Although we maintain separate ledgers for Client and Platform accounts, Platform will have no obligation to segregate by blockchain address the Digital Currencies owned by you from the Digital Currencies of other clients or The Platform.",
  
  item37: "2.7. Fiat wallets. ",
  
  item38: "The wallets denominated in national currencies are internal denominations used by the Platform to represent digital assets translated into the national nomenclatures of the countries according to their own scale and exchange rates, in no case are they considered real national fiduciary values, so their value of settlement or exchange with other national currencies may vary regardless of the official or private exchange rates for which said currencies are traded. Your National Currency Wallets allow you to retain and transfer with your Platform Account to local banks in the countries where the Platform maintains banking intermediation operations through locally authorized partners or agents. If the Platform does not have agent partners or authorized operators in any jurisdiction, said currencies may be exchanged for other national currencies to be withdrawn by local banks or the Client may also transfer them to other users of the network directly or exchange them for digital assets.",

  item39: "2.8. USDT Wallets. ",
  
  item40: "You can also choose to buy USDT, a digital currency that can be transferred between different platforms that support such protocols. The Platform is not responsible for the value of USDT coins or their settlement in fiat money.",

  item41: "2.9 Additional Platform Services. ",
  
  item42: "The Platform offers multiple digital products or services in one secure transaction, our services are subject to our current rates. The Platform makes available the digital offers included in any package at its sole discretion. The number of services, promotions, packages or products are based on existing availability, for which prices may vary, as well as the speed of delivery, composition or characteristics of each one and the rates and commissions applicable to each of our services.",
  
  item43: "3. Payment Services, Purchase & Sale Transactions",
  
  item44: "3.1.Fund Deposits from Banks. ",
  
  item45: "You can load funds into your Wallets from your validated bank accounts via wire transfer, as long as your registration credentials allow it. Your balance will be pending until we can certify that the money is available and has been transferred from an account owned by the Client, and will not be credited to your Wallet until the bank transfer has been settled, the receipt of bank money will be on behalf of our authorized operators depending on the country or region you are in. The name of your linked bank account and your bank transfer must match the name verified in your account on The Platform. In some cases transfers can take hours or even days to clear. In some countries there are restrictions that can delay or even cancel some of the deposit or transfer operations, in these cases you will be informed and the operation will be canceled without the right to claim because they are causes that remain beyond our control. Transfers made within the United States are only enabled for clients expressly authorized by the Platform, any deposit within the United States at the bank level will be rejected if the Client does not have prior express authorization before making the transfer. In each country, the transfer reception accounts may vary and any deposit or transfer made by mistake to an inactive account in the system will be the sole responsibility of the Client, since the operators may be withdrawn or suspended and the Client must verify previously before making his transfer. If the Client mistakenly transfers to an unauthorized or inactive account on the Platform, the Platform will not be responsible for the amount deposited or transferred.",
  
  item46: "3.2. Purchase or Sale of Digital Currency. ",
  
  item47: "For transactions on The Platform you may purchase (purchase) Digital Currency using: (a) funds in your Wallet, (b) Digital Currency held in certain Digital Currency Wallets, as permitted by The Platform, (c) a valid bank account with the name that matches the name on your Platform account, or (d) a debit or credit card that matches the name on your Platform account, (each a “valid payment method”). Your purchase must follow the relevant instructions indicated on the Platform websites. The Platform reserves the right to cancel any transaction not confirmed by you within five (5) seconds after the Platform quotes the transaction price. A digital currency purchase using a valid payment method will generally be initiated on the business day we receive your instructions. The purchased digital currency will be deposited into your digital currency wallet as soon as the funds have been deposited on the Platform, which, in the case of a bank account or credit or debit card, may take up to five business days or more. You can sell digital currency and direct The Platform to fund your wallet where supported, in a digital currency wallet. Purchases and sales of digital currency are collectively referred to herein as “Digital Currency Transactions”. If The Platform is unable to complete your Digital Currency Transaction for any reason (such as price movement, non-response from systems, or an order that exceeds the maximum order size), The Platform will reject the order and notify you of such rejection. You will not be charged for a declined transaction.",
  
  item48: "3.3. Fee and Rates of Transfers of Digital Assets. ",
  
  item49: "The Platform does not make any profit from transfers, but the Client accepts and acknowledges that transfer fees, also known as mining fees, may vary. The Platform already has a built-in minimum cost per transaction to cover transfer or mining fees. When you send or receive from external platforms, the rates may vary and if they are higher than the minimums already charged by the Platform, they will be deducted from your transfers. The Platform IS NOT RESPONSIBLE FOR THESE EXTRA CHARGES and the Client accepts that they will be debited from their transaction and will not make any claim since the Platform will not cover additional costs for mining transfers or bank commissions.",
  
  item50: "3.4. Recurring, suspicious or high-risk transactions. ",
  
  item50_1: "If you initiate recurring, suspicious Transactions or make deposits or transfers from high-risk accounts or wallets, the Platform may suspend, block, freeze or close your account and You agree that such decision shall be at the sole discretion of the Platform and that You are not obligated to provide you with the reasons for making this decision.",
   
  item51: "3.5. Revocation or Closure. ",
  
  item52: "The Client can close or revoke his account when he deems it necessary without any explanation or approval by the Platform. If the amount in custody is a high amount, the Platform may take up to 30 days to settle the funds considering the settlement of the different positions and the necessary security to verify that the action is exercised by the account holder or authorized person.",
  
  item53: "3.6. Unauthorized and Incorrect Transactions. ",
  
  item54: "When a digital currency transaction occurs using your credentials, we will assume that you authorized such a transaction, unless you notify us otherwise. If you believe that you did not authorize a particular transaction or that a transaction was carried out incorrectly, you should contact us as soon as possible, either by email or by the Attention numbers, remember that digital currency payments are irreversible and a Once made to external platforms, any recovery attempt will be impossible. It is important that you regularly review your Digital Wallet balances and transaction history to ensure as soon as possible of any unauthorized or incorrect transactions. We are not responsible for any claims for unauthorized or incorrect transactions.",
  
  item55: "3.7. Account Information. ",
  
  item56: "You will be able to view your Wallet balances using The Platform website or mobile applications. You will also be able to consult: (a) amount and currency of each Transaction, (b) Cell number of the payer or beneficiary (as applicable), (c) Fee charged (excluding any mining, banking or exchange rate differentials), (d) Fee of exchange received or paid after the exchange, and (e) the date of each Transaction.",
  
  item57: "3.8. Consent to access, process and store your personal data. ",
  
  item58: "You consent to our accessing, processing and retaining any personal information you provide to us for the purpose of providing you with the Platform Services. This consent is not related to, and does not affect, any rights or obligations that we or you have under data protection laws, privacy laws and regulations. You can withdraw your consent at any time by closing your account with us. However, we may retain and continue to process your personal information for other purposes. Please see our Privacy Policy for more information on how we process your personal data and the rights you have in this regard. In case of fraud, the Platform may share your information with local operators or other payment agents that have been defrauded and request the information to recover their money. If you commit any type of fraud such as withdrawals of funds duplicated or obtained by Security Violations, bank reversals or any other form of fraud including third party fraud, your private information may be shared with the affected counterparty and the Platform is not responsible for the use or handling that the payment recovery company or the aggrieved party gives to your private information.",
  
  item59: "3.9. Reversals & Cancellations. ",
  
  item60: "You may not cancel, reverse, or change any transaction marked complete or pending. If your payment is not successful, if your payment method does not have sufficient funds, or if you reverse a payment made with funds in your bank account, you authorize The Platform, its Operators or Authorized Representatives, in their sole discretion, to cancel the payment. transaction or debit from another payment method, including the balances in your Wallets or other linked accounts, any amount necessary to complete the transaction. You are responsible for maintaining an adequate balance or sufficient credit limits to avoid overdrafts, insufficient funds, or similar fees assessed by your payment provider. We reserve the right to refuse to process, cancel or reverse any Digital Currency Transaction or Transfer in our sole discretion, even after funds have been debited from your account, if we suspect that the transaction involves (or has a high risk of involvement in) money laundering, financing of terrorism, fraud or any other type of financial crime; in response to a subpoena, court order, or other government order; if we reasonably suspect that the transaction is in error; or if The Platform suspects that the transaction is related to Prohibited Use or a Prohibited Business. In such cases, The Platform will reverse the transaction and we are under no obligation to allow you to place a buy or sell order at the same price or on the same terms as the canceled transaction.",
  
  item61: "",
  
  item62: "3.10. Payment Services Partners. ",
  
  item63: "The Platform may use a third-party payment processor to process any payments between you and The Platform, including but not limited to payments related to your use of Digital Currency Transactions or deposits or withdrawals from your Wallets.",
  
  item64: "4. Digital Currency Transfers",
  
  item65: "4.1. In General. ",
  
  item66: "If you have sufficiently verified your identity, your Digital Currency Wallet allows you to send Supported Digital Currency and request, receive and store Third Party Digital Currency by instructions through the Platform Site. Your transfer of Supported Digital Currencies between your other Digital Currency Wallets (including off-site wallets on The Platform) and to and from third parties is a “Digital Currency Transfer”.",

  item67: "4.2. Pending Transactions. ",
  
  item68: "Once a digital currency transfer is sent to the digital currency network, the transaction will not be confirmed and will remain in a pending state for a period of time sufficient for the digital currency network to confirm the transaction. A digital currency transfer is not complete while it is in pending status. Pending digital currency transfers that are initiated from a Platform account will reflect a pending transaction status and will not be available for use on The Platform while the transaction is pending. It may also be pending for review or security processes, especially when they are new accounts or without prior history of operations, said security and control process may take from a few hours to several days and may even be canceled if the General Administrator detects any behavior strange, suspicious or unusual in the corresponding account registered in the Platform.",
  
  item69: "4.3. Incoming digital currency transfers. ",
  
  item70: "When you or a third party send digital currency to a Platform wallet from an external wallet not hosted on The Platform (“Incoming Transfers”), the person initiating the transaction is solely responsible for executing the transaction correctly, which may include , among other things, paying enough network or miner fees for the transaction to be successful or even sending a coin through the wrong network. Insufficient network fees may cause an incoming Transfer to remain in a pending status beyond the control of The Platform and We are not responsible for any delays or losses incurred as a result of an error in initiating the transaction and we have no obligation to assist. in such transactions. By initiating an incoming transfer, you attest that you are transacting in a supported digital currency that matches the particular Platform wallet to which the funds are directed. For example, if you select a bitcoin wallet address to receive funds, you attest that you are initiating an Incoming Bitcoin Transfer and not in any other currency such as Bitcoin Cash or Bitcoin CSV for example. The Platform incurs no obligation with respect to unsupported digital currency sent to a Platform account or supported digital currency sent to an unsupported digital currency wallet. Funds transmitted in error will be forfeited. We recommend that customers send a small amount of supported digital currency as evidence before initiating a significant amount of supported digital currency. The Platform may determine from time to time the types of digital currency that will or will no longer be supported.",

  item71: "4.4. Outgoing digital currency transfers. ",
  
  item72: "When you send digital currency from your Platform account to an external wallet (“Outgoing Transfers”), the Platform executes such transfers according to your instructions. You must verify all transaction information before submitting instructions to us. The Platform will not bear any responsibility in case you enter an incorrect blockchain destination address. We do not guarantee the identity or the value received by a recipient of an outgoing transfer. Digital currency transfers cannot be reversed once they have been transmitted to the corresponding digital currency network, although they may be in a pending state and designated accordingly while network operators process the transaction. The Platform does not control the Digital Currency network and does not guarantee that the network will confirm a Digital Currency Transfer. We may refuse to process or cancel any pending Outgoing Digital Currency Transfer as required by law or any court or other authority to which The Platform is subject in any jurisdiction. In addition, you may be required to wait for some time after completing a transaction before allowing you to use more Platform Services and/or before allowing you to transact beyond certain volume limits.",

  item73: "4.5. Transfers to a recipient's affiliated email address or mobile number. ",
  
  item74: "The Platform allows you to initiate a digital currency transfer to a client of The Platform with that client's cell phone number. If you initiate a digital currency transfer to an affiliated mobile number and the recipient does not have a Platform account, we will invite them to open a Platform account. If the recipient does not open a Platform account within 6 hours, we will return the corresponding digital currency to their digital currency wallet.",

  item75: "4.6. Trades or payments to third parties. ",
  
  item76:  "We have no control or responsibility for the delivery, quality, safety, legality or any other aspect of the goods or services that you may purchase from a third party using the Platform's wallets as a means of payment. If you experience a problem with any goods or services purchased or sold from a third party using the Platform, or if you have a dispute with such a third party, you must resolve the dispute directly with that third party. If you believe a third party has engaged in fraudulent, deceptive, or inappropriate behavior, or if you are unable to adequately resolve a dispute with a third party, you may notify Platform Support so that we may consider what action to take, if any.",
  
  item77: "4.7 Debts. ",
  
  item78: "In the event that there are outstanding amounts owed to us, The Platform reserves the right to debit your account accordingly and/or withhold amounts from any funds you may transfer from your associated account.",

  item79: "5. Additional Services",
  
  item80: "5.1 Generally. ",
  
  item81: "In addition to the above Services, The Platform may make available the following services (“Additional Services”) for users who meet certain eligibility criteria, such as rewards, GiftCards, Bitcards, partner bonuses, etc., each of which is will publish and any applicant must have a valid account and have maintained a minimum average balance of at least 100 USD in the combined balance of their accounts for the last three months.",
  
  item103: "6. Data Protection and Security",
  
  item104: "6.1. Personal Data. ",
  
  item105: "You acknowledge that we may process personal data in relation to you (if you are an individual), and personal data that you have provided to us or in the future provide to us in relation to your employees and other associated persons in accordance with number 3.8 of this General Agreement. of User or in relation to the Services of the Platform. Accordingly, you represent and warrant that: (a) your disclosure of any personal data relating to persons other than yourself was or will be made in accordance with all applicable data privacy and data protection laws, and those data is accurate, (b) before providing such personal data to us, you have read and understood our Privacy Policy, which is available here, and, in the case of personal data relating to a person other than you, you have (or will have in the time of disclosure) has provided a copy of that Privacy Policy (including future amendments); and (c) if we provide you with a replacement version of the Privacy Policy, you will immediately read that notice and provide a copy to anyone whose personal data you have provided to us.",
  
  item106: "6.2. Security violation. ",
  
  item107 : "Any error, technical, cybernetic, attempted fraud, improper charge on erroneous operations or any other type of situation that involves a Security Violation, and that the Client can detect or presume must be immediately notified to the Platform through any of its channels. regular Attention, if the security flaw is exploited with the intention of obtaining some economic benefit or causing damage to the Platform or any of its Users or associates, the User or the person determined to have used this security violation with an intention malicious may be criminally charged and your private data may be used for legal intimidation against this person, additionally your account may be blocked and blacklisted available to other exchanges or the international crypto financial community.",
  
  item108: "7. General Use, Prohibited Use, Death of Account Owner, and Termination of Agreement. ",
  
  item109: "7.1. Limited License. ",
  
  item110: "We grant you a limited, non-exclusive, non-transferable license, subject to the terms of this Agreement, to access and use the Platform Services, the Platform Site, and related content, materials, and information (collectively, the “Content”). Only for the purposes approved by The Platform. Any other use of the Site or Platform Content is expressly prohibited and all other right, title, and interest in and to the Platform Services, the Site, or the Platform Content are our exclusive property. You agree that you will not copy, transmit, distribute, sell, license, reverse engineer, modify, publish, or participate in the transfer or sale, creation of derivative works, or in any other way exploit the Content in whole or in part. The logos, designs, processes and names are the exclusive property of the Platform.",
  
  item111: "7.2. Website Accuracy. ",
  
  item112: "Although we intend to provide accurate and timely information on the Platform site, the site (including, without limitation, content) may not always be entirely accurate, complete, or current, and may also include technical inaccuracies or typographical errors. . In an effort to continue to provide you with information that is as complete and accurate as possible, information may be changed or updated from time to time without notice, including, but not limited to, information about our policies, products, and services. Consequently, you must verify all the information before any commercial operation, and all decisions based on the information contained in the Platform site are your sole responsibility and we will not have any responsibility for such decisions. Information provided by third parties, including historical price and supply data for digital currencies, is for informational purposes only and The Platform is not responsible for or guarantees its accuracy. Links to third party materials (including, without limitation, websites) may be provided as a convenience to you, but are not controlled by us. You acknowledge and agree that we are not responsible for any aspect of the information, content or services contained in third party materials or third party sites accessible or linked to the Platform Site.",

  item113: "7.3. Promotions. ",
  
  item114: "The Platform may offer special offers or run promotions for customers who qualify. Subject to applicable laws, The Platform or the issuer of a digital currency subject to an offer or promotion may establish qualification criteria for participation in any special promotion in their sole discretion. The Platform may revoke any special offer at any time without notice. Once Digital Currency has been deposited in a user's Digital Currency Wallet, that Digital Currency becomes the property of the user of The Platform with all applicable ownership rights, including those set forth in Section 2.2 of this Agreement. The Platform will have no obligation to offer special offers to all customers. The Platform does not make recommendations or provide any advice on the value or usefulness of any digital currency subject to a promotion.",
  
  item115: "7.4. Third Party Applications. ",
  
  item116: "If, to the extent permitted by The Platform from time to time, you grant express permission to a third party to access or connect to your Platform Account(s), either through the third party's product or service or through The Platform, you acknowledge that granting permission to a third party to take specific actions on your behalf does not relieve you of any of your responsibilities under this Agreement. You are fully responsible for all acts or omissions of any third party with access to your Platform account(s). In addition, you acknowledge and agree that you will not hold The Platform responsible and will indemnify The Platform for any liability arising out of or related to any act or omission of any third party with access to your account on The Platform. You may change or remove the permissions granted by you to third parties with respect to your Platform account(s) at any time through the tabs on the Account Settings page on the Platform site.",

  item117: "7.5. Prohibited Use. ",
  
  item118: "In connection with your use of the Platform Services and your interactions with other users and third parties, you agree and represent that you will not engage in any Prohibited Business or Prohibited Use defined herein. We reserve the right at all times to monitor, review, retain and/or disclose any information as necessary to comply with any applicable law, regulation, sanctions programs, legal process or governmental request. We reserve the right to terminate and/or suspend your Platform Account(s) and/or block transactions or freeze funds immediately and without notice if we determine, in our sole discretion, that your Account is associated with a Use Prohibited and/or a prohibited business.",
  
  item119: "7.6. Transaction Limits. ",
  
  item120: "Use of all Platform Services is subject to a limit on the amount of volume, stated in US dollar terms, You may make transactions or transfers in a given period (for example, daily). To view your limits, log in to your Platform account and visit the Monthly Trading Limits section. Your transaction limits may vary depending on your payment method, the verification steps you've completed, and other factors. The Platform reserves the right to change the applicable limits as we deem necessary in our sole discretion. If you wish to increase your limits beyond the published amounts, please send the request to our official Customer Service channels. We may require you to submit additional information about yourself or your business, provide records, and arrange meetings with The Platform staff (such process, “Enhanced Due Diligence”). The Platform reserves the right to charge You the costs and fees associated with enhanced due diligence (DDC), provided that We notify You in advance of the accumulation of such charges. At our sole discretion, we may refuse to increase your limits or we may lower your limits at a later time, even if you have completed enhanced due diligence (CDD).",
  
  item121: "7.7. Suspension, Termination, and Cancellation. ",
  
  item122: "The Platform may: (a) suspend, restrict, or terminate your access to any or all Platform services, and/or (b) deactivate or terminate your Account. Reasons for freezing funds: (1) Subpoena, court order, or binding order from an officially recognized government authority; (2) We reasonably suspect that you are using your Platform Account in connection with a Prohibited Use or Business; (3) Your use of your Account on The Platform is subject to any pending litigation, investigation, or governmental proceeding and/or we perceive an increased risk of legal or regulatory noncompliance associated with your Account activity; (4) Our service partners cannot endorse your use; (5) You take any action that the Platform deems to circumvent the Platform's controls, including, but not limited to, opening multiple Platform accounts or abusing any promotions The Platform may offer or breaching security.",
  
    item122_1: "If The Platform suspends or closes your account, or terminates your use of The Platform services for any reason, we will notify you of our actions unless a court order or other legal process prohibits The Platform from providing you with such notice. You acknowledge that The Platform's decision to take certain actions, including limiting access, suspending or closing your account, may be based on confidential criteria that are essential to The Platform's security and risk management protocols. You agree that The Platform is under no obligation to disclose the details of its security and risk management procedures.",
  
  item122_2:"You will be permitted to transfer Digital Currency or funds associated with your Multi-Currency Wallet for ninety (90) days after Account deactivation or cancellation, unless such transfer is prohibited (a) by law, including, but not limited to, applicable sanction programs, or (b) by means of an apparently valid subpoena or court order. You can cancel your account on The Platform at any time by withdrawing all balances. You will not be charged for canceling your Platform account, although you will be required to pay any outstanding amounts due to The Platform. You authorize us to cancel or suspend any pending transactions at the time of cancellation.",
  
  item123: "7.8. Death of Account Holder. ",
  
  item124: "For security reasons, if we receive legal documentation confirming your death or other information that leads us to believe that you are deceased, we will freeze your Platform Account and during this time, no transactions can be completed until: (i) your designated fiduciary you have opened a new Platform account, as described below, and your entire Platform account has been transferred to such new account, or (ii) we have received proof in a form satisfactory to us that you have not died . If we have reason to believe that you may be deceased but we do not have proof of your death to our satisfaction, you authorize us to make such inquiries, either directly or through third parties, as we deem necessary to ascertain whether you are deceased. Upon receipt of proof satisfactory to us that he is deceased, the trustee he has appointed in a valid will or similar testamentary document must open a new Platform account. If you have not appointed a fiduciary, then we reserve the right to (a) treat as your fiduciary any person entitled to inherit your Platform Account, as determined by us upon receipt and review of documentation that we, in our sole and absolute discretion we deem necessary or appropriate, including (but not limited to) a will, living trust, or affidavit of estate, or (b) requiring an order appointing a trustee from a court having competent jurisdiction over your estate. In the event that we determine, in our sole and absolute discretion, that there is uncertainty regarding the validity of the fiduciary appointment, we reserve the right to seek an order resolving such issue from a court of competent jurisdiction before taking any related action. with your Platform account in accordance with the foregoing, the opening of a new Platform account by a designated fiduciary is mandatory after the death of the owner of a Platform account, and you hereby agree that your fiduciary shall open a new account of The Platform and provide the information required in Section 2 of this Agreement to obtain access to the content of your Account of The Platform.",
  
  item125: "7.9. Unclaimed Property. ",
  
  item126: "If The Platform has funds (whether fiat or digital currency) in your account, and The Platform is unable to contact you and has no record of your use of the Services for several years, applicable law may require The Platform to report these funds (including fiat currency and digital currency) as unclaimed property to the applicable jurisdiction. If this occurs, The Platform will attempt to locate you at the address shown in our records, but if The Platform is unable to locate you, you may be required to surrender such funds to the appropriate state or jurisdiction as unclaimed property.",
  
  item127: "7.10. Relationship of the Parties. ",
  
  item128: "The Platform is an independent contractor for all purposes. Nothing in this Agreement shall be deemed or is intended to be deemed to be, or shall cause, you and The Platform to be treated as partners, joint ventures or otherwise as joint associates for profit, or for you or The Platform to be treated as the agent of the other.",

  item129: "7.11. Privacy of Others; Marketing. ",
  
  item130: "If you receive information about another user through the Platform Services, you must keep the information confidential and only use it in connection with the Platform Services. You may not disclose or distribute a user's information to a third party or use the information, except as reasonably necessary to perform a transaction and other functions reasonably incidental to it, such as support, reconciliation and accounting, unless you receive the express consent of the user to do so. You may not send unsolicited email to a user through the Platform Services.",

  item131: "7.12. Password Security; Contact Information. ",
  
  item132: "You are responsible for creating a strong password and for maintaining the security and proper control of any and all IDs, passwords, hints, personal identification numbers (PINs), API keys or any other code you use to access the Platform Services. Any loss or compromise of the above information or your personal information may result in unauthorized access to your Account on The Platform by third parties and the loss or theft of any Digital Currency or funds in your Account, including your bank accounts and linked credit cards. You are responsible for keeping your email address and phone number current in your Account Profile in order to receive notices or alerts that we may send you. You should never allow remote access or share your computer screen with another person when you are logged into your Platform account. The Platform will never, under any circumstances, ask you for your IDs, passwords or 2-factor authentication codes. We assume no responsibility for any loss you may suffer due to unauthorized use of account login credentials due to causes beyond The Platform and failure to follow or act on any notices or alerts we may send you. In the event that you believe that the information in your Platform account has been compromised, contact the Platform immediately through the official service channels.",
  
  item133: "7.13. Developer Tools. ",
  
  item134: "If you use the developer features of the Services, including but not limited to the APIs of The Platform, you must separately agree to our Developer Agreement when you register your application with The Platform.",
  
  item135: "7.14. Taxes. ",
  
  item136: "It is your sole responsibility to determine whether, and to what extent, taxes apply to transactions you make through the Platform Services, and to withhold, collect, report, and remit the correct amounts of taxes to the appropriate tax authorities. Your transaction history is available through your account on the Platform.",
  
  item137: "7.15. We do not advise and provide investment recommendations. ",
  
  item138: "For the avoidance of doubt, The Platform does not provide legal, tax or investment advice, nor does The Platform's broker operate on its behalf. All trades on The Platform are executed automatically, within the parameters of your order instructions and in accordance with published trade execution procedures, and you are solely responsible for determining whether any investment, investment strategy or related transaction is appropriate for you based on your personal investment objectives, financial circumstances and risk tolerance. You should consult your legal or tax professional regarding your specific situation. The Platform may provide educational information about supported digital currencies, as well as digital currencies not supported by the Platform, in order to help users learn more about such digital currencies. Information may include, but is not limited to, blog posts, articles, links to third-party content, news feeds, tutorials, and videos. The information provided on this website or any third party site does not constitute investment advice, financial advice, trading advice or any other kind of advice, and you should not treat the content of the website as such. The Platform does not recommend that you should buy, earn, sell or hold any digital currency. Before making any decision to buy, sell or hold any digital currency, you should conduct your own due diligence and consult your financial advisors before making any investment decisions. The Platform is not responsible for the decisions you make to buy, sell or hold digital currency based on the information provided by the Platform.",
  
  item139: "8. Customer Feedback, Queries, Complaints, and Dispute Resolution",
  
  item140: "8.1. Contact The Platform. ",
  
  item140_0: "If you have general comments or questions, please contact us through our website through the official Customer Service channels. When you contact us, please provide us with your name, address, and affiliate cell phone number. We may request any other information that we may need to identify you and to be able to respond to requests for information, inquiries or complaints about your account. You can also place an operation in Claim directly through the Claims Option in your operations carousel, by performing this procedure your operation enters directly to the Users' Rights Defender area (Ombudsman) who will analyze your case and give you a resolution or response as soon as possible.",
  
  item140_1: "If you believe your account has been compromised, you can also report your claim by calling +1(201) 989.6074. The Platform will deliver all related legal documents (including civil citations, complaints and minor claims) to the agent registered as the Ombudsman for the service of the claim process. Please note that our registered agent will accept the claim or complaint only if the User is fully identified. By accepting service of a legal document, The Platform does not waive any objections we may have and may raise in response to such document.",
  
  item141: "8.2. Formal Complaint Process. ",
  
  item142: "If you have a dispute with The Platform (a “Claim”), you agree to contact The Platform through our support team to attempt to resolve such dispute amicably. If we are unable to resolve the dispute through The Platform's support team, you and we agree to use the Grievance Process set forth below. You agree to use this process before filing any claims for arbitration or legal action. If you do not follow the procedures set forth in this Section before filing an arbitration claim or lawsuit, we will have the right to ask the arbitrator or court to dismiss your filing until you complete the following steps.",
  
  item143: "8.2.1. Procedural Steps. ",
  
  item144: "In the event that your dispute with The Platform is not resolved through your contact with Platform Support, you agree to use our Complaint form to describe your Complaint, how you would like us to resolve the Complaint, and any other information related to your dispute. that you think is relevant. The claim form can be requested from The Platform's customer service.",
  
  item145: "8.2.2. Platform Response. ",
  
  item146: "We will acknowledge receipt of your claim form after you submit it. A Platform customer relations agent (“Agent”) will review your claim. The Agent will assess your Claim based on the information he has provided and the information in the possession of The Platform. Within 15 business days of receiving your claim form, the agent will address the issues raised on your claim form by sending you an email (“Notice of Resolution”) in which the agent: (1) offers to resolve your claim in the way you requested; (2) Denial of your Complaint and state the reasons for the denial; or (3i) offer to resolve your Claim with an alternative solution. In exceptional circumstances, if the Agent cannot respond to your Claim within 15 business days for reasons beyond the control of The Platform, the Agent will send you a communication indicating the reasons for any delay in responding to your Claim and specifying the date limit by which the Agent will respond to your Claim, which will be no later than 35 business days from receipt of your Claim form.",
  
  item147: "8.3. Arbitration; Class Action Waiver. ",
  
  item148: "If we are unable to resolve the dispute through the Grievance Process, we will first refer your complaint to the Ombudsman, you and we agree that any dispute arising out of or related to this The Platform, including but not limited to legal claims, claims at law of the local jurisdiction of operation, and those based on contract, tort, fraud, misrepresentation, or any other legal theory, shall be resolved by binding arbitration, on a individually (the “Arbitration Agreement”). Subject to applicable jurisdictional requirements, you may elect to pursue your claim in your local small claims court rather than through arbitration as long as your matter remains in small claims court and proceeds only on an individual (not class or representative) basis. ). Arbitration will be conducted in accordance with the uniform arbitration rules of the country where the transaction or claim originated. For cases based in the United States of America, action will be taken through the American Arbitration Association for the arbitration of consumer-related disputes, accessible at: https://www.adr.org/sites/default/files/Consumer% 20Rules.pdf).",
   
  item149: "This Arbitration Agreement includes, without limitation, disputes arising out of or related to the interpretation or application of the Arbitration Agreement, including the applicability, revocability, scope, or validity of the Arbitration Agreement or any part of the Arbitration Agreement. All of these matters will be decided by an arbitrator and not by a court or judge.",
  
  item150: "CLASS ACTION WAIVER: TO THE EXTENT PERMITTED BY LAW, ALL CLAIMS MUST BE BROUGHT IN THE CAPACITY OF A PARTY INDIVIDUALLY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY CLASS, CLASS ACTION, OR REPRESENTATIVE PROCEEDING (“WAIVER OF CLASS ACTION COLLECTIVE”). THE ARBITRATOR MAY NOT CONSOLIDATE MORE THAN ONE PERSON'S CLAIMS OR PARTICIPATE IN ANY CLASS ARBITRATION. YOU ACKNOWLEDGE THAT, BY AGREEING TO THESE TERMS, YOU AND COINBASE ARE WAIVING THE RIGHT TO A TRIAL BY JURY AND THE RIGHT TO PARTICIPATE IN A CLASS ACTION.",

  item151: "Arbitration will be conducted by a single, neutral arbitrator and will be conducted in the jurisdiction in which you reside, or at another mutually agreeable location. The arbitrator may award any relief that may be awarded by a court of competent jurisdiction and the arbitral decision may be enforced in any court. The decision and judgment of an arbitrator in this regard will not have an effect of prior or collateral preclusion. Upon request, hearings may be held in person or by telephone and the arbitrator may order motions to be filed and determined in writing, without oral hearings. To the extent permitted by law, the prevailing party in any action or proceeding to enforce this Agreement, any arbitration under this Agreement, or any small claims action shall be entitled to costs and attorneys' fees. If the arbitrator or arbitration administrator imposes filing fees or other administrative costs on you, we will reimburse you, upon request, to the extent such fees or costs exceed what you would otherwise have to pay if you were proceeding in court. We will also pay additional fees or costs if required by the arbitration administrator's rules or applicable law.",
  
  item152: "9. General Provisions",
  
  item153: "9.1. Computer Viruses. ",
  
  item154: "We assume no responsibility, whatsoever, for any damage or interruption caused by computer viruses or other malicious code that may affect your computer or other equipment, or any phishing, phishing or other type of attack. We recommend the regular use of reputable and readily available virus detection and prevention software. You should also be aware that email and SMS services are vulnerable to phishing and phishing attacks and you should be careful when reviewing messages that purport to originate from The Platform. Always to review any required transaction or action if you have any doubts regarding the authenticity of any communication or advice.",
  
  item155: "9.2. Compensation. ",
  
  item156: "If you have a dispute with one or more users of The Platform Services, you release The Platform, its affiliates and service providers, and each of their respective officers, directors, agents, joint ventures, employees and representatives from any and all one claims, demands and damages (actual and consequential) of every kind and nature arising out of or in any way related to such disputes. You agree to indemnify and hold The Platform, its affiliates and service providers, and each of their respective officers, directors, agents, joint ventures, employees and representatives, harmless from any claim or demand (including attorneys' fees and fines), fees or penalties imposed by any regulatory authority arising out of or related to your breach of this Agreement or your violation of any law, rule or regulation, or the rights of any third party.",
  
  item157: "9.3. Limitation of Liability. ",
  
  item158: "The Platform its members, directors, workers or related under no circumstances will be responsible for (A) Any amount greater than the balances deposited in your account (B) For any loss, decrease, business opportunity or any incidental, direct or indirect loss or damage indirect tangible or intangible property, consequential or related to the use of the Platform arising from authorized or unauthorized use or from the possibility of damages arising from failures being originated under the use of the Platform or any binding activity such as falling in the systems, software failures, acts of sabotage, suspension of services whether directly or indirectly related to the activities or purposes of the Platform, even under direct responsibility of what is contemplated in this Agreement. You agree that no claim will proceed beyond the funds deposited in your wallet provided by the Platform. The Platform offers the service as is without any guarantee for accidental or incidental failures whether or not they are the direct responsibility of the Platform directly and You waive any claim for damages of any nature for amounts greater than those deposited or handled within the Platform.",
  
  item158_1: "IF YOU CLAIM THAT THE PLATFORM DID NOT CORRECTLY PROCESS A PURCHASE OR SALE TRANSACTION, YOUR DAMAGES ARE LIMITED TO NO MORE THAN THE VALUE SUPPORTED IN THE TRANSACTION, AND YOU MAY NOT RECOVER OR CLAIM FOR LOST PROFITS, LOST BUSINESS OPPORTUNITIES, REDUCTION IN VALUE OR OTHER TYPES OF SPECIAL, INCIDENTAL, INDIRECT, INTANGIBLE, EXEMPLARY, PUNITIVE OR CONSEQUENTIAL DAMAGES IN EXCESS OF VALUE SUPPORTING DIGITAL CURRENCY IN ISSUANCE IN THE TRANSACTION. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU.",
  
  item159: "THE PLATFORM SERVICES ARE PROVIDED “AS IS” AND “AS AVAILABLE” WITHOUT ANY REPRESENTATION OR WARRANTY, EITHER EXPRESS, IMPLIED OR STATUTORY. TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, THE PLATFORM SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE. THE PLATFORM MAKES NO REPRESENTATION OR WARRANTY THAT ACCESS TO THE SITE, ANY PART OF THE PLATFORM SERVICES, OR ANY OF THE MATERIALS CONTAINED THEREIN, WILL BE CONTINUOUS, UNINTERRUPTED, TIMELY, OR ERROR-FREE. THE PLATFORM DOES NOT WARRANT THAT ANY ORDER WILL BE EXECUTED, ACCEPTED, SAVED OR REMAIN OPEN. EXCEPT FOR THE EXPRESS STATEMENTS SET FORTH IN THIS AGREEMENT, YOU ACKNOWLEDGE AND AGREE THAT YOU HAVE NOT RELYED ON ANY OTHER STATEMENT OR UNDERSTANDING, WHETHER WRITTEN OR ORAL, WITH RESPECT TO YOUR USE OF AND ACCESS TO THE PLATFORM SERVICES AND ANY INCLUDED SITE. WITHOUT LIMITING THE FOREGOING, YOU UNDERSTAND AND AGREE THAT THE PLATFORM SHALL NOT BE LIABLE FOR ANY LOSS OR DAMAGE ARISING OUT OF OR RELATED TO: (A) ANY INACCURACIES, DEFECTS OR OMISSIONS OF DIGITAL CURRENCY PRICE DATA OR DELAY IN TRANSMISSION OF SUCH DATA, OR (C) INTERRUPTION OF SUCH DATA.",
  
  item159_1: "The Platform is not responsible for the accuracy, order, timeliness or completeness of historical digital currency price data available on The Platform site. The Platform will make all reasonable efforts to ensure that electronic debit and credit requests involving bank accounts, credit cards, and check issuance are processed in a timely manner, but The Platform makes no representations or warranties regarding the amount of time necessary to complete the processing which depends on many factors beyond our control.",
  
  item160: "9.4. Severability. ",
  
  item161: "If any provision of this Agreement is found to be invalid or unenforceable under any rule, law, or regulation of any local, state, or federal government agency, such provision will be changed and construed to achieve the purposes of the provision to the fullest extent. to the extent possible under any applicable law and the validity or enforceability of any other provision of this Agreement shall not be affected.",
  
  item162: "9.5. Control change. ",
  
  item163: "In the event that The Platform is acquired or merged with a third party entity, we reserve the right, in any of these circumstances, to transfer or assign the information that we have collected from you as part of such merger, acquisition, sale, or another change of control.",
  
  item164: "9.6. Survival. ",
  
  item165: "All provisions of this Agreement that, by their nature, extend beyond the expiration or termination of this Agreement, including, without limitation, sections relating to suspension or termination, cancellation of The Platform account, debts incurred , general use of The Platform, disputes and general provisions will survive the termination or expiration of this Agreement.",
  
  item166: "9.7. Governing Law. ",
  
  item167: "This agreement is governed by the Basel Convention and the statutes of the World Trade Organization, the application of local jurisdiction will be carried out by the Operators or Authorized Representatives of the platform in any of the countries where it maintains commercial operations as long as respect the International Agreements universally approved for carrying out commercial exchanges and the Regulations issued by the FATF on the prevention of money laundering and money laundering and activities related to terrorism.",
   
  item168: "9.8. Overwhelming force. ",
  
  item169: "We will not be responsible for delays, failures in performance or interruption of service resulting directly or indirectly from any cause or condition beyond our reasonable control, including but not limited to, significant market volatility, any delay or failure due to any act of God, act of civil or military authorities, act of terrorism, civil disturbance, war, strike or other labor dispute, fire, interruption in telecommunications or Internet services or network provider services, equipment or software failure, other catastrophe or any other event that is beyond our reasonable control and will not affect the validity and enforceability of any remaining provisions.",
  
  item170: "10. Final Declaration on Risk. ",
  
  item171: "10.1. Like any asset, managing funds backed by digital currencies can go down as well as up and there may be a substantial risk that you will lose money buying, selling, holding or investing in digital currencies. You should carefully consider whether trading or holding digital currencies is right for you in light of your financial situation. The Platform is not registered with the US Securities and Exchange Commission or any country, and does not offer securities services in the United States or to US persons. You acknowledge that digital currencies are high risk and that you may lose money due to high market volatility and that under no circumstances will the Platform be liable for losses caused by market volatility.",
  
  }

}
  