export default {
  item1:"I declare that I make this Bitcoin Purchase to my satisfaction at the rate provided by DLBTC and that it appears on the Receipt / Ticket of the transaction. I am informed and agree by means of this Statement that I give my consent that any charge made by the bank will be debited at the same rate as my final deposit in Bitcoin that will be credited to my Wallet.",
  item2:"I declare and accept that likewise any Tax or extra Payment caused by the Government, the Bank or any other authority of the Country where I make this Purchase, may be debited from the final balance of my deposit in Bitcoin. I also declare that in case there is a delay in the reception and availability of my payment to the subsidiary Operator's account of DLBTC.com, the platform will be able to recalculate the final amount of my deposit based on the current rate for the moment in that funds are available in the Local Operator account of DLBTC.com.",
  item3:"I declare under oath that the payment I am making comes from my account registered in my DLBTC.com user profile, in case I made an error from a third party account, or from an account owned by another bank that is not authorized for this transaction, as a valid means of payment, I will immediately notify the Operator DLBTC.com, so that he can seek a solution or reverse the deposit made as soon as possible. In case my payment is made from a third party account or from an account of my property not registered for this operation, I accept that the payment will be CANCELED," +
    " likewise the Purchase Operation and the money will be withheld until some of the the following actions: a) that my account of another bank can be validated and registered, b) that if the payment comes from a third party, this or it can register in a valid way in the Platform and certify its payment, so that it is accredited to the new User. In the event that the Operator can be positively demonstrated the validity of the payment, a penalty of ten percent (10%) of the net amount of the operation and a rate adjustment will be applied for the moment that the Payment is certified. In any other case, the User will be suspended and the funds in his Wallet blocked until the Banking Revenue is finalized. The expenses for operations, commissions and reimbursements will be calculated once the process is finished and will be debited from the funds in custody of the client before proceeding to the return of the remaining in the case that there is.",
  item4:"I declare that the funds with which I make this Purchase are my property and are not the product of Illicit activities. I declare that I am of legal age and with legal power to make this Purchase and that before doing it I have informed myself of all the legal aspects in force in my country of residence, to buy and sell cryptoactives. Any legal limitation, whether it be payment of Taxes or Taxes, for the completion of this purchase is my sole responsibility.",
  item5:"I declare that this Purchase is Irreversible and that in order to conclude the process I will make the agreed payment in this Transaction according to the Ticket generated automatically by the System, under the agreed procedure, fulfilling the steps requested by the Operator. Once the Payment is made, I will proceed to attach the corresponding certificate of the same under the requested terms. In the event that the Operator requires more documentation to support the Operation, I will proceed to provide the same in order to validate the sending of the funds from my Registered Account.",
  item6:"I declare that I know in advance that any contravention of the agreed rules may result in the suspension or definitive cancellation of the Purchase with the consequences described above.",
  item7:"I declare under oath that all the data provided by me for the realization of this Purchase operation are true.",
  item8:"I declare that I am the owner of the Wallet registered under my name on DLBTC.com and that I agree to receive the Bitcoin purchased therein under the Terms and Conditions set forth in the Ticket / Transaction Receipt to my full and complete satisfaction."
}