export default {
ters: { 
      item1: "ACUERDO GENERAL DE USUARIO",
  item2: "Este es un Acuerdo de Servicio entre Usted (también denominado en este documento “Cliente” o “Usuario”) y la multi plataforma on line de servicios criptograficos: moneyclick.com o sus sitios web asociados: dollarbtc.com y bitcoinrecharge.com, (denominadas colectivamente de ahora en adelante “La Plataforma”) y sus respectivas extensiones como las aplicaciones móviles para Android o IOS . La Plataforma está constituida por un conjunto de programas informáticos que prestan diferentes servicios, como ventas en línea, servicios de comunicación, entretenimiento, información y servicios crypto financieros. Para disfrutar de los servicios ofrecidos por La Plataforma el Cliente debe poseer saldo el cual se ofrece a través de la venta de nuestro cupones electrónicos de servicio, comercializados en la monedas de curso legal en los distintos países donde La Plataforma presta servicios a través de sus Operadores o Representantes Locales Autorizados. Este Acuerdo de Usuario (“Acuerdo”) rige el uso de los servicios proporcionados por La Plataforma que se describen a continuación (“Servicios de la Plataforma”). Al registrarse para usar una cuenta en La Plataforma usted acepta que ha leído, comprende y acepta todos los términos y condiciones contenidos en este Acuerdo, incluyendo las cláusulas de: Arbitraje; Política de Privacidad, Política de Cookies y Política de Consentimiento de Firma Electrónica.",
  item3: "I PARTE",
  item4: "USO GENERAL",
  item5: "1. Requisitos para ser Usuario de La Plataforma:",
  item6: "1.1. Elegibilidad. ",
  item7 : "Para ser elegible para utilizar los Servicios de La Plataforma, debe tener al menos 18 años.",
  item8: "1.2. Condiciones. ",
  item9: "Podemos enmendar o modificar este Acuerdo en cualquier momento publicando el acuerdo revisado en el sitio web de La Plataforma o proporcionándole una copia (un “Acuerdo Revisado”) por cualquier canal registrado de comunicación. El Acuerdo revisado entrará en vigencia a partir del momento en que se publique, pero no se aplicará retroactivamente. Su uso continuado de los Servicios después de la publicación de un Acuerdo revisado constituye su aceptación de dicho acuerdo modificado. Si no está de acuerdo con dicha modificación, su único y exclusivo recurso es terminar su uso de los Servicios de La Plataforma y cerrar su cuenta.",

  item10: "1.3. Registro de cuenta en La Plataforma. ",

  item11: "Debe registrarse para obtener una cuenta de La Plataforma para poder disfrutar y utilizar los Servicios prestados en La Plataforma. Al utilizar una cuenta de La Plataforma, usted acepta y declara que utilizará La Plataforma sólo para usted y no en nombre de un tercero, a menos que haya obtenido la aprobación previa de La Plataforma. Usted es completamente responsable de toda la actividad que ocurra en su cuenta de La Plataforma. Podemos, a nuestro exclusivo criterio, negarnos a abrir una Cuenta en La Plataforma, o limitar el número de cuentas, suspender o cancelar cualquier cuenta de La Plataforma.",

  item12: "1.4.Verificación de identidad. ",
  
  item13: "Durante el registro de su cuenta de La Plataforma, acepta proporcionarnos la información que solicitamos con el fin de verificar la identidad y la detección de lavado de dinero, financiamiento del terrorismo, fraude o cualquier otro delito financiero y nos permite mantener un registro de dicha información. Deberá completar ciertos procedimientos de verificación antes de que se le permita utilizar los Servicios de La Plataforma. Su acceso a uno o más Servicios de La Plataforma y los límites que se aplican a su uso de los Servicios de La Plataforma pueden modificarse como resultado de la información recopilada sobre usted de forma continua. La información que solicitamos puede incluir cierta información personal, que incluye, entre otros, su nombre, dirección, número de teléfono, dirección de correo electrónico, fecha de nacimiento, número de identificación del contribuyente, una identificación del gobierno e información sobre su cuenta bancaria (como el nombre del banco, el tipo de cuenta, el número de ruta y el número de cuenta) y, en algunos casos (donde lo permita la ley), categorías especiales de datos personales, como su información biométrica. Al proporcionarnos esta o cualquier otra información que pueda ser necesaria, usted confirma que la información es precisa y auténtica. Acepta mantenernos actualizados si cambia la información que nos proporcione. Usted nos autoriza a realizar las consultas, ya sea directamente o a través de terceros, que consideremos necesarias para verificar su identidad o protegerlo a usted y a nosotros contra el fraude u otro delito financiero, y para tomar las medidas que consideremos razonablemente necesarias en función de los resultados de tales consultas. Cuando llevamos a cabo estas consultas, usted reconoce y acepta que su información personal puede ser divulgada a agencias de referencia crediticia y prevención de fraude o delitos financieros y que estas agencias pueden responder a nuestras consultas en su totalidad. Esta es solo una verificación de identidad y no debería tener ningún efecto adverso en su calificación crediticia. También autoriza a su operador inalámbrico de telefonía a usar su número de teléfono móvil, nombre, dirección, correo electrónico, estado de la red, tipo de cliente, función del cliente, facturación tipo, identificadores de dispositivos móviles (IMSI e IMEI) y otros detalles del estado del suscriptor, si están disponibles, únicamente para permitir la verificación de su identidad y para comparar la información que ha proporcionado a La Plataforma con la información del perfil de su cuenta mientras se mantenga la duración  de relación comercial. Si desea obtener información adicional sobre nuestra Política de Privacidad y protección de datos puede revisar nuestro Contrato de Servicios de Protección de Datos o consultar directamente por nuestro correo de Atención al Cliente sobre dichas políticas.",
  
  item14: "1.5. Acceso. ",
  
  item15: "Para acceder a los Servicios de La Plataforma, debe tener el equipo necesario (como un teléfono inteligente o una computadora portátil o de escritorio) y las suscripciones de servicios de telecomunicaciones asociadas para acceder a Internet. Se puede acceder a los Servicios de La Plataforma directamente mediante el nuestro sitio web o nuestras aplicaciones móviles. El acceso a los Servicios de La Plataforma puede degradarse o no estar disponible durante épocas de volatilidad o volumen significativo. Esto podría incidir en la disponibilidad de nuestros servicios durante períodos de tiempo y también puede provocar demoras en el tiempo de respuesta del soporte. Aunque nos esforzamos por brindarle un servicio excelente, no declaramos que el o los sitios operados por La Plataforma estarán disponibles sin interrupción y no garantizamos que ningún pedido se ejecutará, aceptará, registrará o permanecerá abierto. La Plataforma no será responsable de las pérdidas que resulten o surjan de retrasos en las transacciones o cualquier servicio inconcluso, interrumpido o retrasado por cualquiera de estas causas u otras ajenas a nuestra voluntad como fallas en la cobertura de internet, fallas eléctricas o incluso problemas propios de equipos defectuosos o sobresaturados en su memoria o por uso excesivo por El Cliente, o fallas de los prestadores de servicios como empresas de telefonía, empresas de transmisión de datos, empresas eléctricas u otros relacionados.",
  

  item16: "2. Servicios de billetera y custodia",
  
  item17: "2.1. Servicios de billetera. ",
  
  item18: "Como parte de su cuenta en La Plataforma, le brindaremos a Los Usuarios que califiquen acceso a billeteras de moneda digital alojadas para guardar activos digitales.",
  
  item19: "2.2. Billetera de moneda digital incorporada. ",
  
  item20: "Su billetera de moneda digital le permite almacenar, rastrear, transferir y administrar sus saldos de moneda digital. “Moneda digital” se refiere sólo a las monedas digitales en particular que se enumeran como disponibles para negociar o custodiar en su Cuenta Multidivisas de La Plataforma. Los servicios y los activos respaldados pueden variar según la jurisdicción. Almacenamos de forma segura las claves privadas de moneda digital, que se utilizan para procesar transacciones, en una combinación de almacenamiento en línea y fuera de línea. Como resultado de nuestros protocolos de seguridad, puede ser necesario que recuperemos claves privadas o información relacionada del almacenamiento fuera de línea para facilitar una Transferencia de moneda digital de acuerdo con sus instrucciones, y usted reconoce que esto puede retrasar el inicio o acreditación de tales Transferencias de Moneda Digital. Es posible que se apliquen reglas adicionales asociadas con dichos productos y servicios.",
  
  item21: "2.3. Monedas digitales admitidas. ",
  
  item22: "Su cuenta de La Plataforma está destinada únicamente para el uso adecuado de las monedas digitales admitidas según lo designado en el sitio. Bajo ninguna circunstancia debe intentar utilizar su Monedero de Moneda Digital para almacenar, enviar, solicitar o recibir monedas digitales que no admitimos. La Plataforma no asume ninguna responsabilidad en relación con cualquier intento de utilizar su Monedero de Moneda Digital con monedas digitales que no admitamos. Si tiene alguna pregunta sobre las monedas digitales que admitimos actualmente consulte en nuestras páginas web asociadas o solicite información a nuestros canales oficiales de Atención al Cliente.",

  item23: "2.4. Protocolos suplementarios excluidos. ",
  
  item24: "A menos que se anuncie específicamente en los sitios de La Plataforma u otra declaración pública oficial de La Plataforma, las monedas digitales admitidas excluyen todos los demás protocolos y funciones que complementan o interactúan con la moneda digital admitida. Esta exclusión incluye, pero no se limita a: cualquier funcionalidad de contrato inteligente. que puede complementar o interactuar con una moneda digital que admitimos. No use su cuenta de La Plataforma para intentar recibir, solicitar, enviar, almacenar o participar en cualquier otro tipo de transacción o funcionalidad que involucre cualquier protocolo no admitido, ya que La Plataforma no está configurada para detectar, asegurar o procesar estas transacciones y funcionalidades. Cualquier intento de transacción efectuadas en monedas no admitidas serán rechazadas y no nos hacemos responsables por perdidas o cualquier retraso u error producto de envío de monedas no admitidas o protocolos no asociados a la Plataforma. Usted reconoce y acepta que los protocolos complementarios están excluidos de la Moneda digital admitida y que La Plataforma no tiene ninguna responsabilidad por las pérdidas relacionadas con los protocolos complementarios o no admitidos.",
  
  item25: "2.5 Funcionamiento de los protocolos de moneda digital. ",
  
  item26: "No poseemos ni controlamos los protocolos de software subyacentes que rigen el funcionamiento de las monedas digitales admitidas en nuestra plataforma. Generalmente, los protocolos subyacentes son de código abierto y cualquiera puede usarlos, copiarlos, modificarlos y distribuirlos. No asumimos ninguna responsabilidad por el funcionamiento de los protocolos subyacentes y no podemos garantizar la funcionalidad o seguridad de las operaciones de la red. En particular, los protocolos subyacentes pueden estar sujetos a cambios repentinos en las reglas de funcionamiento (incluidas las “bifurcaciones”). Cualquiera de estos cambios operativos importantes puede afectar sustancialmente la disponibilidad, el valor, la funcionalidad y / o el nombre de la moneda digital que almacena en su billetera de moneda digital. La Plataforma no controla el momento ni las características de estos cambios operativos materiales. Es su responsabilidad estar al tanto de los próximos cambios operativos y debe considerar cuidadosamente la información disponible públicamente y la información que La Plataforma pueda proporcionar para determinar si continuará usando una Cuenta de La Plataforma para la Moneda Digital afectada. En el caso de cualquier cambio operativo de este tipo, La Plataforma se reserva el derecho de tomar las medidas que sean necesarias para proteger la seguridad y la protección de los activos mantenidos en La Plataforma, incluida la suspensión temporal de las operaciones de las monedas digitales involucradas y otros pasos necesarios; La Plataforma hará todo lo posible para notificarle su respuesta a cualquier cambio operativo importante; sin embargo, dichos cambios están fuera del control de La Plataforma y pueden ocurrir sin previo aviso. La respuesta de La Plataforma a cualquier cambio operativo material está sujeta a su exclusivo criterio e incluye la decisión de no admitir ninguna nueva moneda digital, bifurcación u otras acciones. Usted reconoce y acepta los riesgos de cambios operativos en los protocolos de moneda digital y acepta que La Plataforma no es responsable de dichos cambios operativos y no es responsable de ninguna pérdida de valor que pueda experimentar como resultado de dichos cambios en las reglas operativas. Usted reconoce y acepta que La Plataforma tiene la discreción exclusiva de determinar su respuesta a cualquier cambio operativo y que no tenemos la responsabilidad de ayudarlo con monedas o protocolos no admitidos.",
  
  item27: "2.6. Custodia y Título de Moneda Digital. ",
  
  item28: "Todas las Monedas Digitales mantenidas en su Monedero de Monedas Digitales son activos de custodia mantenidos por La Plataforma para su beneficio, como se describe con más detalle a continuación.",

  item29: "2.6.1 Propiedad. ",
  
  item30: "La titularidad de la moneda digital permanecerá en todo momento con usted y no se transferirá a La Plataforma. Como propietario de la moneda digital en su billetera digital, deberá asumir todos los riesgos de pérdida de dicha moneda digital. La Plataforma no tendrá ninguna responsabilidad por las fluctuaciones de la moneda digital. Ninguna de las Monedas Digitales en su Monedero de Moneda Digital es propiedad de La Plataforma, o será o podrá ser prestada a La Plataforma; La Plataforma no representa ni trata los activos de las Carteras de moneda digital del usuario como pertenecientes a La Plataforma ni a ninguna de sus empresas asociadas, representantes u Operadores Autorizados. La Plataforma no puede otorgar una garantía real sobre la Moneda digital que se encuentra en su Monedero de moneda digital. Excepto según lo requiera una orden judicial emanada de una autoridad competente, o excepto según lo dispuesto en el presente, La Plataforma no venderá, transferirá, prestará, hipotecaria ni enajenará Moneda digital en su Billetera de moneda digital a menos que usted se lo indique.",
  

  item31:"2.6.2 Control. ",
  
  item32: "Usted controla las monedas digitales que se encuentran en su billetera de moneda digital. En cualquier momento, sujeto a interrupciones, tiempo de inactividad y otras políticas aplicables, puede retirar su moneda digital enviándola a una dirección de cadena de bloques diferente. Mientras continúe custodiando sus monedas digitales con La Plataforma, La Plataforma conservará el control sobre las claves privadas electrónicas asociadas con las direcciones de blockchain operadas por La Plataforma, incluidas las direcciones de blockchain que contienen su moneda digital.",
  
  item33: "2.6.3 Reconocimiento del riesgo. ",
  
  item34: "Usted reconoce que la moneda digital no está sujeta a protecciones o seguros proporcionados por la Federal Deposit Insurance Corporation o la Securities Investor Protection Corporation ni otros organismos reguladores o aseguradores de fondos a nivel local de cualquier entidad jurídica. Así como tampoco están respaldados por entidades oficiales, empresas o ningún otro organismo público o privado.",

  item35: "2.6.4 Monedas digitales no segregadas. ",
  
  item36: "Con el fin de custodiar los activos de manera más segura, La Plataforma puede usar direcciones de blockchain compartidas, controladas por La Plataforma, para mantener las monedas digitales en nombre de los clientes y / o en nombre de La Plataforma. Aunque mantenemos libros contables separados para las cuentas de Clientes y de La Plataforma, La Plataforma no tendrá la obligación de segregar por dirección de cadena de bloques las Monedas digitales de su propiedad de las Monedas digitales de otros clientes o de La Plataforma.",
  
  item37: "2.7. Billeteras Fiat. ",
  
  item38: "Las billeteras denominadas en monedas nacionales, son denominaciones internas utilizadas por la Plataforma para representar activos digitales traducidos a las nomenclaturas nacionales de los países según su propia escala y tasas de intercambio, en ningún caso se consideran valores nacionales reales fiduciarios por lo que su valor de liquidación o intercambio con otras monedas nacionales puede variar independientemente de tipos de cambios oficiales o privados por los que se transen dichas monedas. Sus Billeteras de monedas nacionales le permiten retener y transferir con su Cuenta de La Plataforma a bancos locales de los países donde la Plataforma mantiene operaciones de intermediación bancaria a través de socios o agentes autorizados localmente. Si la Plataforma no posee socios agentes u operadores autorizados en alguna jurisdicción dichas monedas podrán ser canjeadas a otras monedas nacionales para ser retiradas por bancos locales o también el Cliente podrá transferirlas a otros usuarios de la red directamente o cambiarlas por activos digitales.",

  item39: "2.8. Carteras USDT. ",
  
  item40: "También puede optar por comprar USDT, una moneda digital que puede ser transferida entre diferentes plataformas que admiten dichos protocolos. La Plataforma no se hace responsable por el valor de las monedas USDT o su liquidación en dinero fiduciario.",

  item41: "2.9 Servicios Adicionales de La Plataforma. ",
  
  item42: "La Plataforma ofrece múltiples productos o servicios digitales en una transacción segura, nuestros servicios están sujetos a nuestras tarifas actuales. La Plataforma pone a disposición las ofertas digitales incluidas en cualquier paquete a su exclusivo criterio. La cantidad de servicios, promociones, paquetes o productos están basadas en la disponibilidad existente por lo cual los precios pueden variar así como la velocidad de entrega, composición o características de cada uno y las tasas y comisiones aplicables a cada uno de nuestros servicios.",
  
  item43: "3. Servicios de pago, transacciones de compra y venta",
  
  item44: "3.1. Depósitos de Fondos desde Bancos.  ",
  
  item45: "Puede cargar fondos en sus Billeteras desde sus cuentas bancarias validadas mediante transferencia bancaria, siempre y cuando sus credenciales de registro se lo permitan. Su saldo estará pendiente hasta que podamos certificar que el dinero está disponible y ha sido transferido desde una cuenta bajo titularidad del Cliente, y no se acreditará en su Billetera hasta que se haya liquidado la transferencia bancaria, la recepción de dinero bancario será por cuenta de nuestros operadores autorizados dependiendo del país o la región en que se encuentre. El nombre de su cuenta bancaria vinculada y su transferencia bancaria deben coincidir con el nombre verificado en su cuenta de La Plataforma. En algunos casos las transferencias pueden tomar horas o incluso días en hacerse efectivas. En algunos países hay restricciones que pueden retrasar o incluso cancelar alguna de las operaciones de depósitos o transferencias, en estos casos será informado y la operación será cancelada sin derecho a reclamos porque son causas que se mantienen fuera de nuestro control. Las transferencias realizadas dentro de los Estados Unidos sólo están habilitadas para clientes autorizados expresamente por la Plataforma, cualquier depósito dentro de los Estados Unidos a nivel bancario será rechazado si el Cliente no tiene autorización expresa previamente antes de realizar la transferencia. En cada país las cuentas de recepción de transferencias pueden variar y cualquier depósito o transferencia realizada por error a una cuenta inactiva en sistema será absoluta responsabilidad del Cliente, ya que los operadores pueden ser retirados o suspendidos y el Cliente debe verificar previamente antes de realizar su transferencia. Si el Cliente por error transfiere a una cuenta no autorizada o inactiva en la Plataforma, la Plataforma no se hará responsable del monto depositado o transferido.",
  
  item46: "3.2. Compra o Venta de Moneda Digital. ",
  
  item47: "Para transacciones en La Plataforma puede comprar (comprar) Moneda digital usando: (a) fondos en su Billetera, (b) Moneda digital mantenida en ciertas Billeteras de moneda digital, según lo permita La Plataforma, (c) una cuenta bancaria válida con el nombre que coincida con el nombre de su cuenta de La Plataforma, o (d) una tarjeta de débito o crédito que coincida con el nombre de su cuenta de La Plataforma, (cada uno es un “método de pago válido”). Su compra debe seguir las instrucciones relevantes indicadas en los sitios web de La Plataforma. La Plataforma se reserva el derecho de cancelar cualquier transacción no confirmada por usted dentro de los cinco (5) segundos posteriores a que La Plataforma cotice el precio de la transacción. Una compra de moneda digital utilizando un método de pago válido generalmente se iniciará el día hábil en que recibamos sus instrucciones. La moneda digital comprada se depositará en su billetera de moneda digital tan pronto como los fondos se hayan depositado en la Plataforma, lo que, en el caso de una cuenta bancaria o tarjeta de crédito o débito, puede demorar hasta cinco días hábiles o mas. Puede vender moneda digital e indicar a La Plataforma que deposite fondos en su billetera cuando sea compatible, en una billetera de moneda digital. Las compras y ventas de moneda digital se denominan colectivamente en el presente documento “Transacciones de moneda digital”. Si La Plataforma no puede completar su Transacción de moneda digital por cualquier motivo (como movimiento de precios, falta de respuesta de sistemas o un pedido que excede el tamaño máximo de pedido), La Plataforma rechazará el pedido y le notificará dicho rechazo. No se le cobrará por una transacción rechazada.",
  
  item48: "3.3. Tarifa y Tasas de Transferencias de Activos Digitales. ",
  
  item49: "La Plataforma no obtiene ganancias producto de transferencias, pero el Cliente acepta y reconoce que las tasas de transferencias, también conocidas como tasas de minado pueden variar. La Plataforma tiene ya incorporado un costo mínimo por transacción para cubrir las tasas de transferencias o minado. Cuando Usted envía o recibe de plataformas externas las tasas pueden variar y en caso de ser mayores a los mínimos ya cobrados por la Plataforma serán deducidos de su transferencias. La Plataforma NO SE HACE RESPONSABLE POR ESTOS CARGOS EXTRAS y el Cliente acepta que serán debitados de su transacción y no hará ningún reclamo ya que la Plataforma No cubrirá costos adicionales por transferencias de minado ni por comisiones bancarias.",
  
  item50: "3.4. Transacciones recurrentes, sospechosas o de alto riesgo. ",
  
  item50_1: "Si inicia Transacciones recurrentes, sospechosas o realiza depósitos o transferencias de cuentas o billeteras de alto riesgo, la Plataforma podrá suspender, bloquear, congelar o cerrar su cuenta y Usted acepta que dicha decisión será de exclusiva discreción de la Plataforma y que no está obligada a suministrar a usted las razones por las cuales toma esta decisión.",
   
  item51: "3.5. Revocación o Cierre. ",
  
  item52: "El Cliente puede cerrar o revocar su cuenta cuando lo considere necesario sin ningún tipo de explicación o aprobación por parte de la Plataforma. Si el monto en custodia es un monto elevado, la Plataforma puede tomar hasta 30 días para liquidar los fondos considerando la liquidación de las diferente posiciones y las seguridad necesaria para comprobar que la acción está ejercida por el titular de la cuenta o persona autorizada.",
  
  item53: "3.6. Transacciones no autorizadas e incorrectas. ",
  
  item54: "Cuando se produce una transacción en moneda digital utilizando sus credenciales, asumiremos que usted autorizó dicha transacción, a menos que nos notifique lo contrario. Si cree que no autorizó una transacción en particular o que una transacción se llevó a cabo incorrectamente, debe comunicarse con nosotros lo antes posible, ya sea por correo electrónico o por los números de Atención, recuerde que los pagos de moneda digital son irreversibles y una vez realizados a plataformas externas nos será imposible cualquier intento de recuperación. Es importante que revise periódicamente los saldos de su Monedero digital y su historial de transacciones para asegurarse lo antes posible de cualquier transacción no autorizada o incorrecta. No somos responsables de ningún reclamo por transacciones no autorizadas o incorrectas.",
  
  item55: "3.7. Información de la cuenta. ",
  
  item56: "Podrá ver los saldos de sus Monederos utilizando el sitio web de La Plataforma o las aplicaciones móviles. También podrá consultar: (a) monto y moneda de cada Transacción, (b) Número celular del pagador o beneficiario (según corresponda), (c) Tarifa cobrada (excluyendo cualquier tasa de minería, bancaria o diferenciales cambiarios), (d) Tasa de cambio recibida o pagada después del cambio, y (e) la fecha de cada Transacción.",
  
  item57: "3.8. Consentimiento para acceder, procesar y almacenar sus datos personales. ",
  
  item58: "Usted da su consentimiento para que accedemos, procesamos y retengamos cualquier información personal que nos proporcione con el propósito de que le brindemos los Servicios de La Plataforma. Este consentimiento no está relacionado con, y no afecta, ningún derecho u obligación que nosotros o usted tengamos de acuerdo con las leyes de protección de datos, las leyes y regulaciones de privacidad. Puede retirar su consentimiento en cualquier momento cerrando su cuenta con nosotros. Sin embargo, podemos retener y seguir procesando su información personal para otros fines. Consulte nuestra Política de Privacidad para obtener más información sobre cómo procesamos sus datos personales y los derechos que tiene al respecto. En caso de fraude la Plataforma podrá compartir su información con operadores locales u otros agentes de pago que hayan sido defraudados y soliciten la información para recuperar su dinero. Si Usted comete cualquier tipo de fraude como retiros de fondos duplicados u obtenidos por Violaciones de Seguridad, reversos bancarios o cualquier otra modalidad de fraude incluidos fraudes a terceros su información privada podrá ser compartida con la contra parte afectada y la Plataforma no se hace responsable por el uso o manejo que el recuperador de pagos o la parte agraviada le de a su información privada.",
  
  item59: "3.9. Reversiones y cancelaciones. ",
  
  item60: "No puede cancelar, revertir ni cambiar ninguna transacción marcada como completa o pendiente. Si su pago no es exitoso, si su método de pago no tiene fondos suficientes, o si revierte un pago realizado con fondos en su cuenta bancaria, usted autoriza a La Plataforma, sus Operadores o Representantes Autorizados, a su sola discreción, a cancelar la transacción o debitar de otro método de pago, incluidos los saldos de sus Monederos u otras cuentas vinculadas, cualquier monto necesario para completar la transacción. Usted es responsable de mantener un saldo adecuado o límites de crédito suficientes para evitar sobregiros, fondos insuficientes o cargos similares cobrados por su proveedor de pagos. Nos reservamos el derecho de negarnos a procesar, cancelar o revertir cualquier Transacción o Transferencia de Moneda Digital a nuestro exclusivo criterio, incluso después de que los fondos hayan sido debitados de su cuenta, si sospechamos que la transacción involucra (o tiene un alto riesgo de implicación en) blanqueo de capitales, financiación del terrorismo, fraude o cualquier otro tipo de delito financiero; en respuesta a una citación, orden judicial u otra orden gubernamental; si sospechamos razonablemente que la transacción es errónea; o si La Plataforma sospecha que la transacción se relaciona con el Uso Prohibido o un Negocio Prohibido. En tales casos, La Plataforma revertirá la transacción y no tenemos la obligación de permitirle establecer una orden de compra o venta al mismo precio o en los mismos términos que la transacción cancelada.",
  
  item61: "",
  
  item62: "3.10. Socios de servicios de pago. ",
  
  item63: "La Plataforma puede utilizar un procesador de pagos de terceros para procesar cualquier pago entre usted y La Plataforma, incluidos, entre otros, los pagos relacionados con su uso de Transacciones en moneda digital o depósitos o retiros de sus Billeteras.",
  
  item64: "4. Transferencias de moneda digital",
  
  item65: "4.1. En general. ",
  
  item66: "Si ha verificado suficientemente su identidad, su Monedero de moneda digital le permite enviar Moneda digital admitida y solicitar, recibir y almacenar Moneda digital de terceros mediante instrucciones a través del Sitio de La Plataforma. Su transferencia de monedas digitales admitidas entre sus otras carteras de moneda digital (incluidas las carteras fuera del sitio La Plataforma) y hacia y desde terceros es una “transferencia de moneda digital”.",

  item67: "4.2. Transacciones pendientes. ",
  
  item68: "Una vez que se envía una transferencia de moneda digital a la red de esa moneda, la transacción no se confirmará y permanecerá en estado pendiente durante un período de tiempo suficiente para que la red de moneda digital confirme la transacción. Una transferencia de moneda digital no está completa mientras está en estado pendiente. Las transferencias de moneda digital pendientes que se inician desde una cuenta de La Plataforma reflejarán un estado de transacción pendiente y no estarán disponibles para su uso en La Plataforma mientras la transacción esté pendiente. Tambien podra estar pendiente por procesos de revisión o seguridad, sobre todo cuando sean cuentas nuevas o sin historial previo de operaciones, dicho proceso de seguridad y control podrá tomar de algunas horas a varios días e incluso podrá ser cancelado si el Administrador General detecta algún comportamiento extraño, sospechoso o no habitual en la cuenta correspondiente registrada en La Plataforma.",
  
  item69: "4.3. Transferencias entrantes de divisas digitales. ",
  
  item70: "Cuando usted o un tercero envía moneda digital a una billetera de La Plataforma desde una billetera externa no alojada en La Plataforma (“Transferencias entrantes”), la persona que inicia la transacción es la única responsable de ejecutar la transacción correctamente, lo que puede incluir, entre otras cosas, el pago de suficientes tarifas de red o minero para que la transacción sea exitosa o incluso por el envío de una moneda a través de una red errónea. Las tarifas de red insuficientes pueden hacer que una Transferencia entrante permanezca en un estado pendiente fuera del control de La Plataforma y no somos responsables de las demoras o pérdidas incurridas como resultado de un error en el inicio de la transacción y no tenemos la obligación de ayudar en tales transacciones. Al iniciar una transferencia entrante, usted da fe de que está realizando una transacción en una moneda digital admitida que se ajusta a la billetera de La Plataforma en particular a la que se dirigen los fondos. Por ejemplo, si selecciona una dirección de billetera bitcoin para recibir fondos, da fe de que está iniciando una Transferencia entrante de bitcoin y no en ninguna otra moneda como Bitcoin Cash o Bitcoin CSV por ejemplo. La Plataforma no incurre en obligación alguna con respecto a la moneda digital no admitida enviada a una cuenta de La Plataforma o la moneda digital admitida enviada a una billetera de moneda digital incompatible. Los fondos transmitidos por error se perderán. Recomendamos a los clientes que envíen una pequeña cantidad de moneda digital admitida como prueba antes de iniciar el envío de una cantidad significativa de moneda digital admitida. La Plataforma puede determinar de vez en cuando los tipos de moneda digital que serán compatibles o dejarán de ser compatibles.",

  item71: "4.4.Transferencias de divisas digitales salientes. ",
  
  item72: "Cuando envía moneda digital desde su cuenta de La Plataforma a una billetera externa (“Transferencias salientes”), La Plataforma ejecuta dichas transferencias según sus instrucciones. Debe verificar toda la información de la transacción antes de enviarnos las instrucciones. La Plataforma no asumirá responsabilidad alguna en caso de que ingrese una dirección de destino de blockchain incorrecta. No garantizamos la identidad o el valor recibido por un destinatario de una transferencia saliente. Las transferencias de moneda digital no se pueden revertir una vez que se han transmitido a la red de moneda digital correspondiente, aunque pueden estar en un estado pendiente y designadas en consecuencia, mientras que los operadores de red procesan la transacción. La Plataforma no controla la red de Divisas Digitales y no garantiza que la red confirme una Transferencia de Divisas Digitales. Podemos negarnos a procesar o cancelar cualquier Transferencia de moneda digital saliente pendiente según lo requiera la ley o cualquier tribunal u otra autoridad a la que La Plataforma esté sujeto en cualquier jurisdicción. Además, es posible que se necesite que espere un tiempo después de completar una transacción antes de permitirle utilizar más Servicios de La Plataforma y / o antes de permitirle realizar transacciones más allá de ciertos límites de volumen.",

  item73: "4.5. Transferencias a la dirección de correo electrónico o número de celular afiliado de un destinatario. ",
  
  item74: "La Plataforma le permite iniciar una transferencia de moneda digital a un cliente de La Plataforma con el número de celular de ese cliente. Si inicia una transferencia de moneda digital a un número de celular afiliado y el destinatario no tiene una cuenta de La Plataforma, lo invitaremos a abrir una cuenta de La Plataforma. Si el destinatario no abre una cuenta de La Plataforma en un plazo de 6 horas, le devolveremos la moneda digital correspondiente a su billetera de moneda digital.",

  item75: "4.6. Comercios o pagos a terceros. ",
  
  item76:  "No tenemos control ni responsabilidad por la entrega, la calidad, la seguridad, la legalidad o cualquier otro aspecto de los bienes o servicios que pueda comprar a un tercero usando como medio de pago las billeteras de la Plataforma. Si experimenta un problema con cualquier bien o servicio comprado o vendido a un tercero utilizando la Plataforma, o si tiene una disputa con dicho tercero, debe resolver la disputa directamente con ese tercero. Si cree que un tercero se ha comportado de manera fraudulenta, engañosa o inapropiada, o si no puede resolver adecuadamente una disputa con un tercero, puede notificar al Soporte de La Plataforma para que podamos considerar qué acción tomar, si corresponde.",
  
  item77: "4.7 Deudas. ",
  
  item78: "En el caso de que haya montos pendientes que se nos adeuden, La Plataforma se reserva el derecho de debitar su cuenta en consecuencia y / o retener montos de los fondos que pueda transferir desde su cuenta asociada.",

  item79: "5. Servicios Adicionales",
  
  item80: "5.1 Generalmente. ",
  
  item81: "Además de los Servicios anteriores, La Plataforma puede poner a disposición los siguientes servicios (“Servicios adicionales”) para los usuarios que cumplan con ciertos criterios de elegibilidad, como recompensas, GiftCards, Bitcards, bonificaciones por asociados, etc, cada una de esta se publicará y cualquier aspirante debe tener una cuenta válida y haber mantenido un saldo promedio mínimo de por lo menos 100 USD en el balance combinado de sus cuenta por los últimos tres meses.",
  
  item103: "6. Protección y seguridad de datos",
  
  item104: "6.1. Información personal. ",
  
  item105: "Usted reconoce que podemos procesar datos personales en relación con usted (si es un individuo), y datos personales que nos haya proporcionado o que en el futuro nos proporcione en relación con sus empleados y otras personas asociadas de acuerdo al número 3.8 de este Acuerdo General de Usuario o en relación a los Servicios de La Plataforma. En consecuencia, usted declara y garantiza que: (a) su divulgación de cualquier dato personal relacionado con otras personas que no sea usted mismo se realizó o se hará de acuerdo con todas las leyes de protección de datos y privacidad de datos aplicables, y esos datos son precisos, (b) antes de proporcionarnos dichos datos personales, ha leído y comprendido nuestra Política de Privacidad, que está disponible aquí y, en el caso de datos personales relacionados con una persona que no sea usted, tiene (o tendrá en el momento de divulgación) haya proporcionado una copia de esa Política de Privacidad (incluyendo futuras modificaciones); y (c) si le proporcionamos una versión de reemplazo de la Política de Privacidad, leerá de inmediato ese aviso y proporcionará una copia a cualquier persona cuyos datos personales nos haya proporcionado.",
  
  item106: "6.2. Violación de la Seguridad. ",
  
  item107 : "Cualquier error, técnico, cibernético, intento de fraude, cobro indebido sobre operaciones erróneas o cualquier otro tipo de situación que involucre una Violacion de Seguridad, y que el Cliente pueda detectar o presumir deberá ser de inmediato notificado a la Plataforma por cualquiera de sus canales regulares de Atención, si la falla de seguridad es aprovechada con intenciones de obtener algun beneficio economico o causar un daño a la Plataforma o cualquiera de sus Usuarios o asociados, el Usuario o la persona que se determine a usado esta violacion de seguridad con una intención maliciosa podrá ser acusado penalmente y sus datos privados podrán ser usados para la intimación legal contra esta persona, adicionalmente su cuenta podrá ser bloqueada y puesto en las listas negras a disposición de otros exchange o la comunidad crypto financiera a nivel internacional.",
  
  item108: "7. Uso general, uso prohibido, muerte del titular de la cuenta y rescisión del Contrato. ",
  
  item109: "7.1. Licencia limitada. ",
  
  item110: "Le otorgamos una licencia limitada, no exclusiva e intransferible, sujeta a los términos de este Acuerdo, para acceder y utilizar los Servicios de La Plataforma, el Sitio de La Plataforma y el contenido, los materiales y la información relacionados (colectivamente, el “Contenido”) únicamente para los fines aprobados por La Plataforma. Cualquier otro uso del Sitio o Contenido de La Plataforma está expresamente prohibido y todos los demás derechos, títulos e intereses en los Servicios de La Plataforma, el Sitio o el Contenido de La Plataforma son propiedad exclusiva. Usted acepta que no copiará, transmitirá, distribuirá, venderá, licenciará, aplicará ingeniería inversa, modificará, publicará ni participará en la transferencia o venta, creación de trabajos derivados, ni explotación de ninguna otra manera del Contenido de forma total o parcial. Los logos, diseños, procesos y nombres son exclusiva propiedad de la Plataforma.",
  
  item111: "7.2. Precisión del sitio web. ",
  
  item112: "Aunque tenemos la intención de proporcionar información precisa y oportuna en el sitio de La Plataforma, es posible que el sitio (incluido, entre otros, el contenido) no siempre sea del todo exacto, completo o actual y también puede incluir imprecisiones técnicas o errores tipográficos. En un esfuerzo por continuar brindándole información lo más completa y precisa posible, la información puede cambiarse o actualizarse de vez en cuando sin previo aviso, incluida, entre otros, información sobre nuestras políticas, productos y servicios. En consecuencia, debe verificar toda la información antes cualquier operación comercial, y todas las decisiones basadas en la información contenida en el sitio La Plataforma son de su exclusiva responsabilidad y nosotros no tendremos ninguna responsabilidad por tales decisiones. La información proporcionada por terceros, incluidos los datos históricos de precios y suministro de monedas digitales, es solo para fines informativos y La Plataforma no se responsabiliza ni garantiza su precisión. Los enlaces a materiales de terceros (incluidos, entre otros, sitios web) se pueden proporcionar para su conveniencia, pero no están controlados por nosotros. Usted reconoce y acepta que no somos responsables de ningún aspecto de la información, el contenido o los servicios incluidos en los materiales de terceros o en los sitios de terceros accesibles o vinculados al Sitio de La Plataforma.",

  item113: "7.3. Promociones. ",
  
  item114: "La Plataforma puede ofrecer ofertas especiales o realizar promociones para los clientes que califiquen. Sujeto a las leyes aplicables, La Plataforma o el emisor de una moneda digital sujeta a una oferta o promoción pueden establecer criterios de calificación para participar en cualquier promoción especial a su exclusivo criterio. La Plataforma puede revocar cualquier oferta especial en cualquier momento sin previo aviso. Una vez que la Moneda Digital se ha depositado en la Cartera de Moneda Digital de un usuario, esa Moneda Digital pasa a ser propiedad del usuario de La Plataforma con todos los derechos de propiedad aplicables, incluidos los indicados en la Sección 2.2 de este Acuerdo. La Plataforma no tendrá la obligación de ofrecer ofertas especiales a todos los clientes. La Plataforma no hace recomendaciones ni proporciona ningún consejo sobre el valor o la utilidad de ninguna moneda digital sujeta a una promoción.",
  
  item115: "7.4. Aplicaciones de terceros. ",
  
  item116: "Si, en la medida permitida por La Plataforma de vez en cuando, otorga permiso expreso a un tercero para acceder o conectarse a su (s) Cuenta (s) de La Plataforma, ya sea a través del producto o servicio del tercero o mediante La Plataforma, usted reconoce que otorgar permiso a un tercero para tomar acciones específicas en su nombre no lo exime de ninguna de sus responsabilidades bajo este Acuerdo. Usted es totalmente responsable de todos los actos u omisiones de cualquier tercero con acceso a su (s) cuenta (s) de La Plataforma. Además, usted reconoce y acepta que no responsabilizará a La Plataforma y indemnizará a La Plataforma por cualquier responsabilidad que surja de o esté relacionada con cualquier acto u omisión de cualquier tercero con acceso a su cuenta de La Plataforma. Puede cambiar o eliminar los permisos otorgados por usted a terceros con respecto a su (s) cuenta (s) de La Plataforma en cualquier momento a través de las pestañas de la página Configuración de la cuenta en el sitio La Plataforma.",

  item117: "7.5. Uso prohibido. ",
  
  item118: "En relación con su uso de los Servicios de La Plataforma y sus interacciones con otros usuarios y terceros, usted acepta y representa que no participará en ningún Negocio Prohibido o Uso Prohibido definido en este documento. Nos reservamos el derecho en todo momento de monitorear, revisar, retener y / o divulgar cualquier información según sea necesario para cumplir con cualquier ley, regulación, programas de sanciones, proceso legal o solicitud gubernamental aplicable. Nos reservamos el derecho de cancelar y / o suspender su (s) Cuenta (s) de La Plataforma y / o bloquear transacciones o congelar fondos inmediatamente y sin previo aviso si determinamos, a nuestro exclusivo criterio, que su Cuenta está asociada con un Uso Prohibido y / o un negocio prohibido.",
  
  item119: "7.6. Límites de transacciones. ",
  
  item120: "El uso de todos los Servicios de La Plataforma está sujeto a un límite en la cantidad de volumen, establecido en términos de dólares estadounidenses, Usted puede realizar transacciones o transferencias en un período determinado (por ejemplo, diariamente). Para ver sus límites, inicie sesión en su cuenta de La Plataforma y visite la sección de límites mensuales de Operaciones. Los límites de sus transacciones pueden variar según su método de pago, los pasos de verificación que haya completado y otros factores. La Plataforma se reserva el derecho de cambiar los límites aplicables según lo consideremos necesario a nuestro exclusivo criterio. Si desea aumentar sus límites más allá de los montos publicados, envíe la solicitud a nuestros canales oficiales de Atención al Cliente. Es posible que le solicitemos que envíe información adicional sobre usted o su empresa, proporcione registros y organice reuniones con el personal de La Plataforma (dicho proceso, “Diligencia debida mejorada”). La Plataforma se reserva el derecho de cobrar a Usted los costos y tarifas asociados con la diligencia debida mejorada (DDC), siempre que le notificamos con anticipación sobre la acumulación de dichos cargos. A nuestro exclusivo criterio, podemos negarnos a aumentar sus límites o podemos reducir sus límites en un momento posterior, incluso si ha completado la diligencia debida mejorada (DDC).",
  
  item121: "7.7. Suspensión, Terminación y Cancelación. ",
  
  item122: "La Plataforma puede: (a) suspender, restringir o cancelar su acceso a cualquiera o todos los servicios de la Plataforma, y / o (b) desactivar o cancelar su Cuenta. Motivos para congelar fondos: (1) Citación, orden judicial u orden vinculante de una autoridad gubernamental oficialmente reconocida; (2) Tenemos sospechas razonables de que está utilizando su Cuenta de la Plataforma en relación con un Uso o Negocio Prohibido; (3) El uso de su Cuenta en La Plataforma está sujeto a cualquier litigio, investigación o procedimiento gubernamental pendiente y / o percibimos un mayor riesgo de incumplimiento legal o reglamentario asociado con la actividad de su Cuenta; (4) Nuestros socios de servicio no pueden respaldar su uso; (5) Usted realiza cualquier acción que la Plataforma considere que elude los controles de La Plataforma, que incluyen, entre otros, la apertura de varias cuentas de La Plataforma o el abuso de las promociones que La Plataforma puede ofrecer o violacion de seguridad.",
  
    item122_1: "Si La Plataforma suspende o cierra su cuenta, o cancela su uso de los servicios de La Plataforma por cualquier motivo, le notificaremos nuestras acciones a menos que una orden judicial u otro proceso legal prohíba que La Plataforma le proporcione dicho aviso. Usted reconoce que la decisión de La Plataforma de tomar ciertas acciones, incluida la limitación del acceso, la suspensión o el cierre de su cuenta, puede basarse en criterios confidenciales que son esenciales para los protocolos de seguridad y administración de riesgos de La Plataforma. Usted acepta que La Plataforma no tiene la obligación de revelar los detalles de sus procedimientos de seguridad y administración de riesgos.",
  
  item122_2:"Se le permitirá transferir Moneda digital o fondos asociados con su Billetera Multidivisa durante noventa (90) días después de la desactivación o cancelación de la Cuenta, a menos que dicha transferencia esté prohibida (a) en virtud de la ley, incluidos, entre otros, los programas de sanciones aplicables, o (b) mediante una citación u orden judicial aparentemente válida. Puede cancelar su cuenta en La Plataforma en cualquier momento retirando todos los saldos. No se le cobrará por cancelar su cuenta de La Plataforma, aunque se le pedirá que pague los montos pendientes adeudados a La Plataforma. Usted nos autoriza a cancelar o suspender cualquier transacción pendiente en el momento de la cancelación.",
  
  item123: "7.8. Muerte del titular de la cuenta. ",
  
  item124: "Por razones de seguridad, si recibimos documentación legal que confirme su fallecimiento u otra información que nos lleve a creer que ha fallecido, congelaremos su Cuenta de La Plataforma y durante este tiempo, no se podrán completar transacciones hasta que: (i) su fiduciario designado haya abrió una nueva cuenta de La Plataforma, como se describe a continuación, y la totalidad de su cuenta de La Plataforma se ha transferido a dicha nueva cuenta, o (ii) hemos recibido prueba en un formulario satisfactorio para nosotros de que no ha fallecido. Si tenemos motivos para creer que puede haber fallecido pero no disponemos de prueba de su fallecimiento de forma satisfactoria para nosotros, usted nos autoriza a realizar las consultas, ya sea directamente o a través de terceros, que consideremos necesarias para saber si ha fallecido. Una vez que recibamos una prueba satisfactoria para nosotros de que ha fallecido, el fiduciario que haya designado en un testamento válido o un documento testamentario similar deberá abrir una nueva cuenta de La Plataforma. Si no ha designado un fiduciario, entonces nos reservamos el derecho de (a) tratar como su fiduciario a cualquier persona con derecho a heredar su Cuenta de La Plataforma, según lo determinemos al recibir y revisar la documentación que nosotros, en nuestro único y absoluto criterio consideremos necesario o apropiado, incluyendo (pero no limitado a) un testamento, un fideicomiso en vida o una declaración jurada de patrimonio, o (b) requerir una orden que designe a un fiduciario de un tribunal que tenga jurisdicción competente sobre su patrimonio. En caso de que determinemos, a nuestro exclusivo y absoluto criterio, que existe incertidumbre con respecto a la validez de la designación fiduciaria, nos reservamos el derecho de solicitar una orden que resuelva dicho problema de un tribunal de jurisdicción competente antes de tomar cualquier medida relacionada con su cuenta en La Plataforma de conformidad con lo anterior, la apertura de una nueva cuenta de La Plataforma por un fiduciario designado es obligatoria después de la muerte del propietario de una cuenta de La Plataforma, y por la presente acepta que su fiduciario deberá abrir una nueva cuenta de La Plataforma y proporcione la información requerida en la Sección 2 de este Acuerdo para obtener acceso al contenido de su Cuenta de La Plataforma.",
  
  item125: "7.9. Propiedad no reclamada. ",
  
  item126: " Si La Plataforma tiene fondos (ya sea moneda fiduciaria o moneda digital) en su cuenta, y La Plataforma no puede comunicarse con usted y no tiene registro de su uso de los Servicios durante varios años, la ley aplicable puede requerir que La Plataforma informar estos fondos (incluida la moneda fiduciaria y la moneda digital) como propiedad no reclamada a la jurisdicción correspondiente. Si esto ocurre, La Plataforma intentará ubicarlo en la dirección que se muestra en nuestros registros, pero si La Plataforma no puede ubicarlo, es posible que deba entregar dichos fondos al estado o jurisdicción correspondiente como propiedad no reclamada.",
  
  item127: "7.10. Relación de las Partes. ",
  
  item128: "La Plataforma es un contratista independiente a todos los efectos. Nada en este Acuerdo se considerará ni se pretende que se considere, ni hará que usted y La Plataforma sean tratados como socios, empresas conjuntas o de otro modo como asociados conjuntos con fines de lucro, o que usted o La Plataforma sean tratados como el agente del otro.",

  item129: "7.11. Privacidad de otros; Márketing. ",
  
  item130: "Si recibe información sobre otro usuario a través de los Servicios de La Plataforma, debe mantener la información confidencial y solo usarla en relación con los Servicios de La Plataforma. No puede divulgar o distribuir la información de un usuario a un tercero ni utilizar la información, excepto cuando sea razonablemente necesario para realizar una transacción y otras funciones razonablemente incidentales a la misma, como soporte, conciliación y contabilidad, a menos que reciba el consentimiento expreso del usuario para hacerlo. No puede enviar correos electrónicos no solicitados a un usuario a través de los Servicios de La Plataforma.",

  item131: "7.12. Seguridad de contraseña; Información del contacto. ",
  
  item132: "Usted es responsable de crear una contraseña segura y de mantener la seguridad y el control adecuado de todas y cada una de las ID, contraseñas, sugerencias, números de identificación personal (PIN), claves API o cualquier otro código que utilice para acceder a los Servicios de La Plataforma. Cualquier pérdida o compromiso de la información anterior o de su información personal puede resultar en un acceso no autorizado a su Cuenta en La Plataforma por parte de terceros y la pérdida o robo de cualquier Moneda Digital o fondos de su Cuenta, incluidas sus cuentas bancarias y tarjetas de crédito vinculadas. Usted es responsable de mantener su dirección de correo electrónico y número de teléfono actualizados en su Perfil de cuenta para recibir avisos o alertas que podamos enviarle. Nunca debe permitir el acceso remoto o compartir la pantalla de su computadora con otra persona cuando haya iniciado sesión en su cuenta de La Plataforma. La Plataforma nunca, bajo ninguna circunstancia, le pedirá sus identificaciones, contraseñas o códigos de autenticación de 2 factores. No asumimos ninguna responsabilidad por cualquier pérdida que pueda sufrir debido al uso no autorizado de las credenciales de inicio de sesión de la cuenta debido a causas ajenas a La Plataforma y al no seguir o actuar de acuerdo a los avisos o alertas que podamos enviarle. En caso de que crea que la información de su cuenta de La Plataforma se ha visto comprometida, comuníquese con la Plataforma inmediatamente a través de los canales oficiales de atención.",
  
  item133: "7.13. Herramientas de desarrollo. ",
  
  item134: "Si utiliza las funciones de desarrollador de los Servicios, incluidas, entre otras, las API de La Plataforma, debe aceptar por separado nuestro Acuerdo de desarrollador al registrar su aplicación en La Plataforma.",
  
  item135: "7.14. Impuestos.",
  
  item136: "Es su exclusiva responsabilidad determinar si, y en qué medida, los impuestos se aplican a las transacciones que realice a través de los Servicios de La Plataforma, y retener, cobrar, informar y remitir las cantidades correctas de impuestos a las autoridades fiscales correspondientes. Su historial de transacciones está disponible a través de su cuenta en la Plataforma.",
  
  item137: "7.15. No asesoramos y brindamos recomendaciones de inversión. ",
  
  item138: "Para evitar dudas, La Plataforma no proporciona asesoramiento legal, fiscal o de inversiones, ni el corredor de La Plataforma  opera en su nombre. Todas las operaciones de La Plataforma  se ejecutan automáticamente, según los parámetros de las instrucciones de su orden y de acuerdo con los procedimientos de ejecución de operaciones publicados, y usted es el único responsable de determinar si cualquier inversión, estrategia de inversión o transacción relacionada es apropiada para usted en función de sus objetivos personales de inversión, circunstancias financieras y tolerancia al riesgo. Debe consultar a su profesional legal o fiscal con respecto a su situación específica. La Plataforma puede proporcionar información educativa sobre  monedas digitales admitidas, así como monedas digitales no admitidas por La Plataforma, con el fin de ayudar a los usuarios a obtener más información sobre dichas monedas digitales. La información puede incluir, entre otros, publicaciones de blogs, artículos, enlaces a contenido de terceros, fuentes de noticias, tutoriales y videos. La información proporcionada en este sitio web o en cualquier sitio de terceros no constituye asesoramiento de inversión, asesoramiento financiero, asesoramiento comercial o cualquier otro tipo de asesoramiento, y no debe tratar el contenido del sitio web como tal. La Plataforma no recomienda que usted deba comprar, ganar, vender o conservar ninguna moneda digital. Antes de tomar la decisión de comprar, vender o mantener cualquier moneda digital, debe realizar su propia diligencia debida y consultar a sus asesores financieros antes de tomar cualquier decisión de inversión. La Plataforma  no se hace responsable de las decisiones que tome para comprar, vender o mantener moneda digital en función de la información proporcionada por la Plataforma.",
  
  item139: "8. Comentarios, consultas, quejas y resolución de disputas de los clientes",
  
  item140: "8.1. Póngase en contacto con La Plataforma. ",
  
  item140_0: "Si tiene comentarios o preguntas generales, comuníquese con nosotros a través de nuestra página web por los canales oficiales de Atención al Cliente. Cuando se comunique con nosotros, indíquenos su nombre, dirección y número de celular afiliado. Es posible que solicitemos cualquier otra información que podamos necesitar para identificarlo y poder responder o atender peticiones de información, consultas o reclamos sobre su cuenta. También puede colocar una operación en Reclamo directamente por la Opción Reclamos en su carrusel de operaciones, al realizar este procedimiento su operación entra directamente al área de Defensor de los Derechos de los Usuarios (Ombudsman) quien analizará su caso y le dará una resolución o respuesta lo antes posible.",
  
  item140_1: "Si cree que su cuenta ha sido comprometida, también puede informar su reclamo llamando al +1(201) 989.6074. La Plataforma entregará todos los documentos legales relacionados (incluidas las citaciones civiles, quejas y reclamos menores) al agente registrado como Defensor de los Derechos de los Usuarios (Ombudsman) para el servicio del proceso de reclamación. Tenga en cuenta que nuestro agente registrado aceptará el reclamo o queja sólo si el Usuario está plenamente identificado. Al aceptar la notificación de un documento legal, La Plataforma no renuncia a ninguna objeción que podamos tener y que podamos plantear en respuesta a dicho documento.",
  
  item141: "8.2. Proceso formal de quejas. ",
  
  item142: "Si tiene una disputa con La Plataforma  (una “Reclamación”), acepta ponerse en contacto con La Plataforma a través de nuestro equipo de soporte para intentar resolver dicha disputa de manera amistosa. Si no podemos resolver la disputa a través del equipo de soporte de La Plataforma, usted y nosotros aceptamos utilizar el Proceso de queja formal que se establece a continuación. Usted acepta utilizar este proceso antes de presentar cualquier reclamo de arbitraje o acción legal. Si no sigue los procedimientos establecidos en esta Sección antes de presentar un reclamo de arbitraje o una demanda judicial, tendremos derecho a pedirle al árbitro o al tribunal judicial  que desestime su presentación hasta que complete los siguientes pasos.",
  
  item143: "8.2.1. Pasos procesales. ",
  
  item144: "En caso de que su disputa con La Plataforma  no se resuelva a través de su contacto con el Soporte de La Plataforma , acepta utilizar nuestro formulario de Quejas para describir su Queja, cómo le gustaría que resolvamos la Queja y cualquier otra información relacionada con su disputa que cree que es relevante. El formulario de reclamación lo puede solicitar al servicio de atención al cliente de La Plataforma.",
  
  item145: "8.2.2. Respuesta de La Plataforma.  ",
  
  item146: "Acusaremos recibo de su formulario de reclamación después de que lo envíe. Un agente de relaciones con el cliente de La Plataforma  (“Agente”) revisará su reclamo. El Agente evaluará su Reclamación según la información que haya proporcionado y la información en posesión de La Plataforma. Dentro de los 15 días hábiles posteriores a la recepción de su formulario de reclamo, el agente abordará los problemas planteados en su formulario de reclamo enviándole un correo electrónico (“Aviso de resolución”) en el que el agente: (1) ofrecerá resolver su reclamo de la forma que solicitó; (2) Rechazo de su Queja y exponer las razones del rechazo; o (3i) ofrecer resolver su Reclamo con una solución alternativa. En circunstancias excepcionales, si el Agente no puede responder a su Reclamación dentro de los 15 días hábiles por razones fuera del control de La Plataforma, el Agente le enviará una comunicación indicando los motivos de cualquier retraso en la respuesta a su Reclamación y especificando la fecha límite para la cual el Agente responderá a su Reclamación, que será a más tardar 35 días hábiles desde que recibamos su formulario de Reclamación.",
  
  item147: "8.3. Arbitraje; Renuncia a la acción de clase colectiva. ",
  
  item148: "Si no podemos resolver la disputa a través del Proceso de queja formal, remitiremos su queja en primera instancia al Defensor de los Derechos de los Usuarios (Ombudsman), usted y nosotros acordamos que cualquier disputa que surja o esté relacionada con este Acuerdo de Servicios de La Plataforma, incluidas, entre otras, las reclamaciones legales, las reclamaciones de derecho de la jurisdicción local de la operación y los basados en contrato, agravio, fraude, tergiversación o cualquier otra teoría legal, se resolverán mediante arbitraje vinculante, de forma individual (el “Acuerdo de Arbitraje”). Sujeto a los requisitos jurisdiccionales aplicables, puede optar por llevar adelante su reclamo en su tribunal local de reclamos menores en lugar de a través del arbitraje siempre que su asunto permanezca en el tribunal de reclamos menores y proceda sólo de manera individual (no colectiva ni representativa). El arbitraje se llevará a cabo de acuerdo con las reglas uniformes de arbitraje del país donde se originó la transacción o el reclamo. Para casos basados en Estados Unidos de América se tomará la acción mediante de la Asociación Estadounidense de Arbitraje para el arbitraje de disputas relacionadas con el consumidor , accesible en: https://www.adr.org/sites/default/files/Consumer%20Rules.pdf).",
   
  item149: "Este Acuerdo de arbitraje incluye, sin limitación, las disputas que surjan de o estén relacionadas con la interpretación o aplicación del Acuerdo de Arbitraje, incluida la aplicabilidad, revocabilidad, alcance o validez del Acuerdo de Arbitraje o cualquier parte del Acuerdo de Arbitraje. Todos estos asuntos serán decididos por un árbitro y no por un tribunal o juez.",
  
  item150: "RENUNCIA DE DEMANDA COLECTIVA: EN LA MEDIDA EN QUE LO PERMITA LA LEY, TODAS LAS RECLAMACIONES DEBEN SER PRESENTADAS EN LA CAPACIDAD INDIVIDUAL DE UNA PARTE, Y NO COMO DEMANDANTE O MIEMBRO DE CLASE EN CUALQUIER CLASE, ACCIÓN COLECTIVA O PROCEDIMIENTO DE REPRESENTACIÓN (“RENUNCIA COLECTIVA”). EL ÁRBITRO NO PUEDE CONSOLIDAR MÁS DE LOS RECLAMOS DE UNA PERSONA NI PARTICIPAR EN NINGÚN ARBITRAJE COLECTIVO. USTED RECONOCE QUE, AL ACEPTAR ESTOS TÉRMINOS, USTED Y COINBASE RENUNCIAN AL DERECHO A UN JUICIO POR JURADO Y AL DERECHO A PARTICIPAR EN UNA DEMANDA COLECTIVA.",

  item151: "El arbitraje estará a cargo de un árbitro único y neutral y se llevará a cabo en la jurisdicción en la que reside, o en otro lugar de mutuo acuerdo. El árbitro puede otorgar cualquier reparación que pueda otorgar un tribunal de jurisdicción competente y la decisión arbitral puede ser ejecutada en cualquier tribunal. La decisión y el juicio de un árbitro al respecto no tendrán un efecto de preclusión previa o colateral. Si lo solicita, las audiencias se pueden llevar a cabo en persona o por teléfono y el árbitro puede disponer la presentación y determinación de mociones sobre escritos, sin audiencias orales. En la medida en que lo permita la ley, la parte que prevalezca en cualquier acción o procedimiento para hacer cumplir este Acuerdo, cualquier arbitraje de conformidad con este Acuerdo o cualquier acción de reclamos menores tendrá derecho a los costos y honorarios de los abogados. Si el árbitro o el administrador de arbitraje le impone tarifas de presentación u otros costos administrativos, le reembolsaremos, previa solicitud, en la medida en que dichas tarifas o costos excedan los que usted tendría que pagar de otro modo si estuviera procediendo en un tribunal.  También pagaremos tarifas o costos adicionales si así lo requieren las reglas del administrador de arbitraje o la ley aplicable.",
  
  item152: "9. Disposiciones Generales",
  
  item153: "9.1. Virus informáticos. ",
  
  item154: "No asumimos ninguna responsabilidad, en absoluto, por ningún daño o interrupción causados por virus informáticos u otro código malicioso que pueda afectar su computadora u otro equipo, o cualquier ataque de suplantación de identidad, suplantación de identidad u otro tipo de ataque. Recomendamos el uso regular de un software de detección y prevención de virus de buena reputación y fácilmente disponible. También debe tener en cuenta que los servicios de correo electrónico y SMS son vulnerables a ataques de suplantación de identidad y suplantación de identidad y debe tener cuidado al revisar los mensajes que supuestamente se originan en La Plataforma . Siempre  para revisar cualquier transacción o acción requerida si tiene alguna duda con respecto a la autenticidad de cualquier comunicación o aviso.",
  
  item155: "9.2. Indemnización. ",
  
  item156: "Si tiene una disputa con uno o más usuarios de los Servicios de La Plataforma , libera a La Plataforma, sus afiliados y proveedores de servicios, y cada uno de sus respectivos funcionarios, directores, agentes, empresas conjuntas, empleados y representantes de todos y cada uno reclamos, demandas y daños (reales y consecuentes) de todo tipo y naturaleza que surjan de o estén relacionados de alguna manera con tales disputas. Usted acepta indemnizar y mantener a La Plataforma, sus afiliados y proveedores de servicios, y cada uno de sus respectivos funcionarios, directores, agentes, empresas conjuntas, empleados y representantes, indemnes de cualquier reclamo o demanda (incluidos los honorarios de los abogados y las multas), tarifas o sanciones impuestas por cualquier autoridad reguladora que surjan de o estén relacionadas con su incumplimiento de este Acuerdo o su violación de cualquier ley, regla o regulación, o los derechos de cualquier tercero.",
  
  item157: "9.3. Limitación de Responsabilidad. ",
  
  item158: "La Plataforma sus miembros, directores, trabajadores o relacionados bajo ninguna circunstancia serán responsables de (A) Cualquier cantidad mayor a los saldos depositados en su cuenta (B) De cualquier pérdida, disminución, oportunidad de negocios o cualquier pérdida o daño incidental, directa o indirecta de propiedad tangible o intangible, consecuente o relacionada con el uso de la Plataforma que surja por uso autorizado o no o de la posibilidad de daños que se desprenda de fallos siendo originados bajo el uso  de la Plataforma o cualquier actividad vinculante como caída en los sistemas, fallas de software actos de sabotaje, suspensión de servicios ya estén directa o indirectamente relacionados a las actividades o propósitos de la Plataforma, incluso bajo responsabilidad directa de lo contemplado en este Acuerdo usted Acepta que ninguna reclamación procederá mas alla de los fondos depositados en su monedero multivisa suministrado por la Plataforma. La Plataforma ofrece el servicio tal cual sin ninguna garantía por fallas accidentales o incidentales aunque sea o no sean responsabilidad directa de la Plataforma directamente y Usted renuncia a cualquier reclamación de daños de cualquier naturaleza por montos superiores a los depositados o que maneja dentro de la Plataforma. ",
  
  item158_1: " SI USTED RECLAMA QUE LA PLATAFORMA NO PROCESÓ CORRECTAMENTE UNA TRANSACCIÓN DE COMPRA O VENTA, SUS DAÑOS SE LIMITAN A NO MÁS QUE EL VALOR SOPORTADO EN LA OPERACIÓN, Y NO PUEDE RECUPERAR O RECLAMAR POR PÉRDIDA DE BENEFICIOS, PÉRDIDA DE OPORTUNIDADES DE NEGOCIO, DISMINUCIÓN DE VALOR U OTROS TIPOS DE DAÑOS ESPECIALES, INCIDENTALES, INDIRECTOS, INTANGIBLES, EJEMPLARES, PUNITIVOS O CONSECUENTES EN EXCESO DEL APOYO DE VALOR MONEDA DIGITAL EN EMISIÓN EN LA TRANSACCIÓN. ALGUNAS JURISDICCIONES NO PERMITEN LA EXCLUSIÓN O LIMITACIÓN DE DAÑOS INCIDENTALES O CONSECUENTES, POR LO QUE LA LIMITACIÓN ANTERIOR PUEDE NO APLICARSE EN SU CASO.",
  
  item159: "LOS SERVICIOS DE LA PLATAFORMA SE PROPORCIONAN “TAL CUAL” Y “SEGÚN ESTÉ DISPONIBLE” SIN NINGUNA REPRESENTACIÓN O GARANTÍA, YA SEA EXPRESA, IMPLÍCITA O ESTATUTARIA. EN LA MÁXIMA MEDIDA PERMITIDA POR LA LEY APLICABLE, LA PLATAFORMA RENUNCIA ESPECÍFICAMENTE CUALQUIER GARANTÍA IMPLÍCITA DE TÍTULO, COMERCIABILIDAD, IDONEIDAD PARA UN PROPÓSITO PARTICULAR. LA PLATAFORMA NO HACE NINGUNA REPRESENTACIÓN O GARANTÍA DE QUE EL ACCESO AL SITIO, CUALQUIER PARTE DE LOS SERVICIOS DE LA PLATAFORMA O CUALQUIERA DE LOS MATERIALES CONTENIDOS EN EL MISMO, SERÁ CONTINUO, ININTERRUMPIDO, OPORTUNO O SIN ERRORES. LA PLATAFORMA NO GARANTIZA QUE NINGÚN PEDIDO SE EJECUTARÁ, ACEPTARÁ, GRABARÁ O PERMANECERÁ ABIERTO. EXCEPTO POR LAS DECLARACIONES EXPRESAS ESTABLECIDAS EN ESTE ACUERDO, USTED RECONOCE Y ACEPTA QUE NO HA CONFIADO EN NINGUNA OTRA DECLARACIÓN O ENTENDIMIENTO, YA SEA ESCRITO U ORAL, CON RESPECTO A SU USO Y ACCESO A LOS SERVICIOS DE LA PLATAFORMA Y A CUALQUIER SITIO INCLUIDO. SIN LIMITAR LO ANTERIOR, USTED ENTIENDE Y ACEPTA QUE LA PLATAFORMA NO SERÁ RESPONSABLE DE LAS PÉRDIDAS O DAÑOS QUE SURJAN DE O ESTÉN RELACIONADOS CON: (A) CUALQUIER INEXACTITUD, DEFECTO U OMISIÓN DE DATOS DE PRECIO DE MONEDA DIGITAL O RETRASO EN LA TRANSMISIÓN DE DICHOS DATOS, O (C) INTERRUPCIÓN DE DICHOS DATOS.",
  
  item159_1: "La Plataforma no se responsabiliza de la precisión, el orden, la puntualidad o la integridad de los datos históricos de precios de la moneda digital disponibles en el sitio de La Plataforma. La Plataforma hará todos los esfuerzos razonables para garantizar que las solicitudes de débitos y créditos electrónicos que involucren cuentas bancarias, tarjetas de crédito y emisión de cheques se procesen de manera oportuna, pero La Plataforma no hace declaraciones ni garantías con respecto a la cantidad de tiempo necesario para completar el procesamiento que depende de muchos factores fuera de nuestro control.",
  
  item160: "9.4. Divisibilidad. ",
  
  item161: "Si se determina que alguna disposición de este Acuerdo es inválida o inaplicable bajo cualquier regla, ley o reglamento de cualquier agencia gubernamental local, estatal o federal, dicha disposición será cambiada e interpretada para lograr los objetivos de la disposición al máximo. en la medida de lo posible bajo cualquier ley aplicable y la validez o aplicabilidad de cualquier otra disposición de este Acuerdo no se verá afectada.",
  
  item162: "9.5. Cambio de control. ",
  
  item163: "En el caso de que La Plataforma sea adquirida o fusionada con una entidad de terceros, nos reservamos el derecho, en cualquiera de estas circunstancias, de transferir o asignar la información que hemos recopilado de usted como parte de dicha fusión, adquisición, venta, u otro cambio de control.",
  
  item164: "9.6. Supervivencia. ",
  
  item165: "Todas las disposiciones de este Acuerdo que, por su naturaleza, se extienden más allá del vencimiento o terminación de este Acuerdo, incluidas, entre otras, las secciones relacionadas con la suspensión o terminación, la cancelación de la cuenta de La Plataforma, las deudas contraídas, el uso general de La Plataforma, las disputas y las disposiciones generales sobrevivirán a la terminación o expiración de este Acuerdo.",
  
  item166: "9.7. Ley que rige. ",
  
  item167: "Este acuerdo se rige por la Convención de Basilea y los estatutos de la Organización de Comercio Mundial, la aplicación de jurisdicción local será llevada a cabo por los Operadores o Representantes autorizados de La plataforma en cualquiera de los países donde esta mentanga operaciones comerciales siempre y cuando respete los Convenios Internacionales aprobados universalmente para la realización de intercambios comerciales y los Reglamentos emanados de la FATF en materia de prevención del lavado y legitimacion de capitales y actividades relacionadas al terrorismo.",
   
  item168: "9.8. Fuerza mayor.  ",
  
  item169: "No seremos responsables por demoras, fallas en el desempeño o interrupción del servicio que resulten directa o indirectamente de cualquier causa o condición más allá de nuestro control razonable, incluyendo pero no limitado a, volatilidad significativa del mercado, cualquier demora o falla debido a cualquier acto de Dios, acto de autoridades civiles o militares, acto de terroristas, disturbios civiles, guerra, huelga u otra disputa laboral, incendio, interrupción en las telecomunicaciones o servicios de Internet o servicios del proveedor de red, falla del equipo o software, otra catástrofe o cualquier otro suceso que está más allá de nuestro control razonable y no afectará la validez y aplicabilidad de las disposiciones restantes.",
  
  item170: "10. Declaración Final sobre Riesgo. ",
  
  item171: "10.1. Al igual que cualquier activo, el manejo de fondos respaldados en monedas digitales puede subir o bajar y puede haber un riesgo sustancial de que pierda dinero comprando, vendiendo, manteniendo o invirtiendo en monedas digitales. Debe considerar cuidadosamente si comerciar o mantener monedas digitales es adecuado para usted a la luz de su situación financiera. La Plataforma no está registrada en la Comisión de Bolsa y Valores de EE. UU. ni de ningún país, y no ofrece servicios de valores en los Estados Unidos ni a personas estadounidenses. Usted reconoce que las monedas digitales son de alto riesgo y que puede perder dinero por la alta volatilidad del mercado y que bajo ninguna circunstancia la Plataforma será responsable de pérdidas ocasionadas por la volatilidad del mercado.",
  
  }

}
  